### ISSUE TITLE
Microsoft SSO sessions expiring too quickly after 0.70.0 upgrade

### ISSUE THREAD

**Issue by Soleedus** [outline/outline#5532] opened 2023-07-06 16:42 UTC
I'm getting feedback from my users that they are having to constantly authenticate against Outline after I performed an upgrade to version 0.70.0. I'm also experiencing the issue as well -- my logon session used to last until my Azure AD auth token would expire.

No changes have been made to my Azure application or tenant, so I'm uncertain what could be causing the increase in authentication frequency. This does not affect our other applications that use Azure AD SSO.

**To Reproduce**
1. Go to internal Outline URL
2. See "Login with Microsoft"
3. Authenticate
4. Close tab and wait approximately 5-10 minutes
5. Go to internal Outline URL, see "Login with Microsoft" again

**Expected behavior**
Pre-upgrade (v0.69.2 and prior), sessions would last longer until the Azure token itself would expire. Other sites requiring Azure SSO remain logged in, but Outline continues to prompt for Microsoft authentication with much greater frequency than expected.

**Screenshots**
![image](https://github.com/outline/outline/assets/1351381/be97ef4c-0d5e-481a-aafa-0be25b126a7b)
**Outline (please complete the following information):**
- Install: Self hosted, docker stack
- Version: 9d4a1965b07b58ed93e591544db9cf599b5f72c3 (v0.70.0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 114.0.1823.67

**Comment by nh4ttruong** [comment] 2023-07-07 07:12
Similarly, I just had upgrade my outline on first day of week and after that the app usually requires to re-auth to SSO. I think the reason is session timeout. Any update for this minimal convenient?

**Comment by tommoor** [comment] 2023-07-07 11:35
SSO sessions are only invalidated once the token expires and cannot be refreshed. There must be a 10min expiry on the tokens you're receiving from Microsoft?

**Comment by nh4ttruong** [comment] 2023-07-07 12:28
The [document](https://learn.microsoft.com/en-us/azure/active-directory/develop/configurable-token-lifetimes) indicates like what @tommoor say. But SSO sessions still work well and keep more than 10 minutes before v0.70.0 upgradation. Additionally, all of our application (configured with SSO like Outline) still keeps session lifetime up to 24h.

**Comment by tommoor** [comment] 2023-07-07 12:31
Bugs were fixed, it's possible your sessions should have been invalidated earlier in earlier releases and are this is now being done correctly.

If you look in the database under `user_authentications` you can see exactly when the expiry of the token is set to after logging in.

**Comment by santiagobiali** [comment] 2023-07-07 16:46
Same behavior in my local environment: sessions expiring too quickly after 0.70.0.
I'm using Keycloak as authentication realm instead of Microsoft.
In keycloak, sessions are set to 4 hours IDLE timeout before they expire.

Other aplications that also authenticate using keycloak are working fine.

```docker version
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```

OS: Windows 11 22H2
Browser: Google Chrome 114.05735.199

**Comment by tommoor** [comment] 2023-07-07 22:23
Please check if your database has multiple `authentication_providers`

**Comment by routerino** [comment] 2023-07-09 02:12
Same problem, only single authentication provider.

I did notice that my `lastSignedIn` cookie seems to think I signed in a year into the future
![image](https://github.com/outline/outline/assets/45954722/9815b551-8478-4946-a430-f6acb160911b)

**Comment by routerino** [comment] 2023-07-09 03:08
Also having the same problem. Log shows "Refreshing Expired Access Token" and getting 401 errors before getting redirected back to login, but access tokens have a 3 month expiry in the browser.

**Comment by ioki-cha** [comment] 2023-07-10 08:06
Confirming this, since `v0.70.0` people are logged out constantly after short preiods of time. 

@libnewton care to share your fix?

**Comment by ioki-cha** [comment] 2023-07-10 10:29
> It feels insecure and shady.

Ok, definitly looks like a hack with potentially massive security side-effects, still thanks for sharing!

**Comment by tommoor** [comment] 2023-07-10 12:06
Still nobody has provided the one bit of information I asked for to debug this…

**Comment by ioki-cha** [comment] 2023-07-10 12:21
I've had a look at `authentication_providers`, and (at least in my case) there's only a single column. 

Regarding `user_authenications`, I can confirm that the `expiresAt` column is indeed set to ~88 minutes after `updatedAt` (a bit lower than 1.5h - weird). I've done a profile update noop to trigger this. So it logges out in accordance with that. 

I'm currently looking into any setting on the SSOs side that would indicate a expiry, but so far I can't seem to find any.  ~88 minutes seems like a weird default... We followed the docs here and didn't specify anything custom there.

**Comment by tommoor** [comment] 2023-07-10 12:35
The token expiry itself being ~90 minutes is normal (from MS docs: "When issued, an access token's default lifetime is assigned a random value ranging between 60-90 minutes") – this is why we have the refresh token as well, it allows swapping for a new token providing much better security. 

So it must be the refresh process that is failing. I will say that the cloud hosted version is running the same code and has tens of thousands of Microsoft SSO users that are not being kicked out, so most-likely this is somehow specific to self hosting.

You can double check that a refresh token exists in the database, beyond that it's likely that the `https://login.microsoftonline.com/common/oauth2/v2.0/token` token endpoint cannot be reached from your server for some reason

**Comment by ioki-cha** [comment] 2023-07-10 12:50
Thanks for looking into this!

I can reach the endpoint (at least via `curl`), but it indeed seems to be an issue with refreshing the tokens (there's one in my database, but I'm getting these errors in the logs):

```
{"label":"worker","level":"info","message":"ValidateSSOAccessTask running","userId":"XXX"}
{"id":"YYY","label":"utils","level":"info","message":"Refreshing expiring access token","userId":"XXX"}
{"label":"task","level":"info","message":"Authentication token no longer valid for XXX"}
{"error":"Invalid token","level":"error","message":"Authentication error socket XXX","stack":"UnauthorizedError: Invalid token\n    at AuthenticationError (/opt/outline/build/server/errors.js:38:34)\n    at getUserForJWT (/opt/outline/build/server/utils/jwt.js:58:43)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async authenticate (/opt/outline/build/server/services/websockets.js:181:16)\n    at async Socket.<anonymous> (/opt/outline/build/server/services/websockets.js:81:9)"}
```

The respective user has a `refreshToken` set in the database, but I can't tell if it is recent. I'm happy to help debugging this further, any suggestion what to add to `server/utils/oauth.ts` make logging more verbose?

**Comment by tommoor** [comment] 2023-07-10 13:02
You can log:

The value of `valid`:
https://github.com/outline/outline/blob/4bec08ee056ee2203f7677cb762d8376f1cf5601/server/queues/tasks/ValidateSSOAccessTask.ts#L31

The value of `error`:
https://github.com/outline/outline/blob/5fa8ebc587dca1b9b67f48e058164aa1fe64aa8d/server/models/UserAuthentication.ts#L122

Probably keep a note of refresh token to see if it is changing on login.

**Comment by ioki-cha** [comment] 2023-07-10 13:19
When logging out and re-logging in, the `refreshToken` is updated. 

Will report back with more debugging info.

**Comment by ioki-cha** [comment] 2023-07-10 14:18
Here are the logs incl. the `valid` and `error` output:

```
Jul 10 16:15:42 outline yarn[253002]: {"id":"YYY","label":"utils","level":"info","message":"Refreshing expiring access token","userId":"XXX"}
Jul 10 16:15:42 outline yarn[253002]: {
Jul 10 16:15:42 outline yarn[253002]:   error: 'invalid_request',
Jul 10 16:15:42 outline yarn[253002]:   error_description: "AADSTS50194: Application 'AAA'(companyname outline) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.\r\n" +
Jul 10 16:15:42 outline yarn[253002]:     'Trace ID: TTT\r\n' +
Jul 10 16:15:42 outline yarn[253002]:     'Correlation ID: CCC\r\n' +
Jul 10 16:15:42 outline yarn[253002]:     'Timestamp: 2023-07-10 14:15:42Z',
Jul 10 16:15:42 outline yarn[253002]:   error_codes: [ 50194 ],
Jul 10 16:15:42 outline yarn[253002]:   timestamp: '2023-07-10 14:15:42Z',
Jul 10 16:15:42 outline yarn[253002]:   trace_id: 'TTT',
Jul 10 16:15:42 outline yarn[253002]:   correlation_id: 'CCC',
Jul 10 16:15:42 outline yarn[253002]:   claims: '{"access_token":{"capolids":{"essential":true,"values":["ZZZ"]}}}'
Jul 10 16:15:42 outline yarn[253002]: }
Jul 10 16:15:42 outline yarn[253002]: Error: UnauthorizedError: Authentication required
Jul 10 16:15:42 outline yarn[253002]: Valid: false
Jul 10 16:15:42 outline yarn[253002]: {"label":"task","level":"info","message":"Authentication token no longer valid for XXX"}
```

**Comment by tommoor** [comment] 2023-07-10 14:34
Okay, so this was always erroring silently but we made a change that actually fixed the validation logic and now it's correctly logging out. Staying on 0.69.X series is the way to go until a patch – I have all the information needed now 👍

**Comment by ioki-cha** [comment] 2023-07-10 16:08
Thank you, will wait for the fix! Let me know if I can provide more info/ help! 

Side note: Is it safe to downgrade from 0.70.0 to 0.69 as a temporary solution?

**Comment by tommoor** [comment] 2023-07-11 02:31
Probable fix is in the above branch if someone is able to give it a test on a _real_ installation, with confirmation I'll put out a patch release.

**Comment by ioki-cha** [comment] 2023-07-11 12:36
I can confirm I'm not logged out anymore! Tested this on a live instance with several users, With the above debug messages enabled, I'm getting all `valid: true` all the time now.

**Closed** 2023-07-11 22:59 UTC
Labels: bug, self-hosted

**Comment by tommoor** [comment] 2023-07-11 23:17
Fix published in `v0.70.2`

**Comment by routerino** [comment] 2023-07-12 01:23
Note that I tested with the custom branch and it does not appear to be resolved with keycloak using generic oidc as a provider.

I will re-test with the just released version.

**Comment by tommoor** [comment] 2023-07-12 01:33
This issue is specific to Microsoft Azure, if you're being signed out with OIDC provider it will be a different problem.

**Comment by routerino** [comment] 2023-07-12 05:15
Yep, definitely still occuring in the new version for generic OIDC. @tommoor  Do you want me to open a new issue? Relevant (I think) logs with debug enabled:

```
outline             | {"label":"database","level":"debug","message":"Executing (default): UPDATE \"users\" SET \"lastActiveAt\"=$1,\"updatedAt\"=$2 WHERE \"id\" = $3"}
outline             | {"label":"worker","level":"info","message":"ValidateSSOAccessTask running","userId":"acdcc812-abbb-4284-b385-b65eb6f7368b"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): START TRANSACTION;"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): SELECT \"id\", \"scopes\", \"accessToken\", \"refreshToken\", \"providerId\", \"expiresAt\", \"lastValidatedAt\", \"userId\", \"authenticationProviderId\", \"createdAt\", \"updatedAt\" FROM \"user_authentications\" AS \"user_authentication\" WHERE \"user_authentication\".\"userId\" = 'acdcc812-abbb-4284-b385-b65eb6f7368b' FOR UPDATE;"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): SELECT \"id\", \"name\", \"enabled\", \"providerId\", \"teamId\", \"createdAt\" FROM \"authentication_providers\" AS \"authentication_provider\" WHERE \"authentication_provider\".\"id\" = 'da8bdc10-4382-40ee-975e-b7341017d51e';"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): SELECT \"id\", \"name\", \"enabled\", \"providerId\", \"teamId\", \"createdAt\" FROM \"authentication_providers\" AS \"authentication_provider\" WHERE \"authentication_provider\".\"id\" = 'da8bdc10-4382-40ee-975e-b7341017d51e';"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): SELECT \"id\", \"name\", \"enabled\", \"providerId\", \"teamId\", \"createdAt\" FROM \"authentication_providers\" AS \"authentication_provider\" WHERE \"authentication_provider\".\"id\" = 'da8bdc10-4382-40ee-975e-b7341017d51e';"}
outline             | {"id":"817d1c18-b304-4b76-8b1a-e792d772b48e","label":"utils","level":"info","message":"Refreshing expiring access token","userId":"acdcc812-abbb-4284-b385-b65eb6f7368b"}
outline             | {"endpoint":"[Filtered]","label":"utils","level":"debug","message":"Rotating token"}
outline             | {"id":"d8a378e1-8fd2-4fcf-9eba-6ccf83156292","label":"utils","level":"info","message":"Refreshing expiring access token","userId":"acdcc812-abbb-4284-b385-b65eb6f7368b"}
outline             | {"endpoint":"[Filtered]","label":"utils","level":"debug","message":"Rotating token"}
outline             | {"id":"496ccc59-980b-474f-b3e8-3b8c1ddb5359","label":"utils","level":"info","message":"Refreshing expiring access token","userId":"acdcc812-abbb-4284-b385-b65eb6f7368b"}
outline             | {"endpoint":"[Filtered]","label":"utils","level":"debug","message":"Rotating token"}
outline             | {"label":"database","level":"debug","message":"Executing (67144fb7-851d-4ef0-be8d-19582cba9898): SELECT \"id\", \"email\", \"name\", \"isAdmin\", \"isViewer\", \"jwtSecret\", \"lastActiveAt\", \"lastActiveIp\", \"lastSignedInAt\", \"lastSignedInIp\", \"lastSigninEmailSentAt\", \"suspendedAt\", \"flags\", \"preferences\", \"notificationSettings\", \"language\", \"avatarUrl\", \"suspendedById\", \"invitedById\", \"teamId\", \"createdAt\", \"updatedAt\", \"deletedAt\" FROM \"users\" AS \"user\" WHERE (\"user\".\"deletedAt\" IS NULL AND \"user\".\"id\" = 'acdcc812-abbb-4284-b385-b65eb6f7368b') FOR UPDATE;"}
```

**Comment by matbgn** [comment] 2023-07-14 20:28
We have also tested it in prod and can only confirm that we are still logged out too fast since 0.70+ (even last patch have no effect on our OIDC - Keycloack arch).
