### ISSUE TITLE
Multiple authentication providers for the same team

### ISSUE THREAD

**Issue by dorianim** [outline/outline#4401] opened 2022-11-08 06:38 UTC
### Discussed in https://github.com/outline/outline/discussions/4326

As nobody replied here, I figured, it might not be intended beheaviour, so I'll open an issue for it.

<div type='discussions-op-text'>

<sup>Originally posted by **dorianim** October 24, 2022</sup>
Hi,

I'd like to use multiple authentication providers for the same team. The team already has some users using slack and I added an oidc source. The oidc configuration is definitely working, I tested it with a fresh instance of outline.
When I login using the oidc source, I always get the error `invalid-authentication` and this log:
```json
{"error":"Invalid authentication","stack":"UnauthorizedError: Invalid authentication\n at InvalidAuthenticationError (/opt/outline/build/server/errors.js:48:34)\n at accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:69:52)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at async OAuth2Strategy._verify (/opt/outline/build/server/routes/auth/providers/oidc.js:87:22)","level":"error","message":"Error during authentication"}
```

The domain of the oidc users has been whitelisted.
Any idea on how to solve this?</div>

**Comment by tommoor** [comment] 2022-11-08 12:18
There seems to be a bug right now, closing as a duplicate of #4275 which already covers it

**Closed by tommoor** 2022-11-08 12:18 UTC
