### ISSUE TITLE
can not search Chinese characters in title.

### ISSUE THREAD

**Issue by kedizhou** [outline/outline#5428] opened 2023-06-08 10:55 UTC
**To Reproduce**
1. Go to 'Search' in left menu column
2. input Chinese characters in Textbox '祖国'
3. See error：Display blank page, unless, Click 'search only title' or using character '我' for searching condition.

**Expected behavior**
My expect searching Chinese characters in Search function.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![image](https://github.com/outline/outline/assets/1912659/c20c8806-4e56-48d3-bc75-191a4730f344)

**Outline (please complete the following information):**
- Install: [getoutline.com or self hosted]
Answer: self hosted
- Version: [commit sha if self hosted]
Answer: 0.69.2

**Desktop (please complete the following information):**
 Answer: macOS
 Answer: Chrome
 Answer: Version 113.0.5672.126 (Official Build) (arm64)

**Mobile (please complete the following information):**
 Answer: N/A
Answer: N/A
 Answer: N/A

**Comment by tommoor** [comment] 2023-06-08 12:46
Duplicate of #3207 – this is a limitation of Postgres and we'll need to move search index off it to reliably support CJK search.

**Closed by tommoor** 2023-06-08 12:46 UTC
Labels: bug
