### ISSUE TITLE
Don't search Chinese character in documents

### ISSUE THREAD

**Issue by kedizhou** [outline/outline#5680] opened 2023-08-11 02:56 UTC
**To Reproduce**
1. Go to 'search box' in the top of one Document Collection page.
2. Input Chinese character '语言'
4. Display "no search any document for you"

**Expected behavior**
I expect the search function can search Chinese characters.

**Screenshots**
![image](https://github.com/outline/outline/assets/1912659/167bbbd6-9d5b-43b6-ba38-5474cbfdabd1)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.70.2

**Desktop (please complete the following information):**
 - OS: Macbook
 - Browser: Chrome
 - Version: 115.0.5790.114

**Mobile (please complete the following information):**
 - Device: /
 - OS: /
 - Browser /

**Comment by Nedved-liao** [comment] 2023-08-11 03:40
> A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'search box' in the top of one Document Collection page.
> 2. Input Chinese character '语言'
> 3. Display "no search any document for you"
> 
> **Expected behavior** I expect the search function can search Chinese characters.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/1912659/259913451-167bbbd6-9d5b-43b6-ba38-5474cbfdabd1.png)
> 
> **Outline (please complete the following information):**
> 
> * Install: self hosted
> * Version: v0.70.2
> 
> **Desktop (please complete the following information):**
> 
> * OS: Macbook
> * Browser: Chrome
> * Version: 115.0.5790.114
> 
> **Mobile (please complete the following information):**
> 
> * Device: /
> * OS: /
> * Browser /

可以的，只是比较慢
![image](https://github.com/outline/outline/assets/35453327/768b0a67-b365-49f7-bb0a-5d74bc0770c2)

**Comment by tommoor** [comment] 2023-08-11 09:08
Duplicate of https://github.com/outline/outline/issues/3207

**Closed by tommoor** 2023-08-11 09:08 UTC
Labels: bug
