### ISSUE TITLE
Support Newer S3 Nodes

### ISSUE THREAD

**Issue by marforic** [outline/outline#904] opened 2019-02-25 09:47 UTC
S3 requires newer signatures for nodes that were deployed after 2014 (such as Frankfurt https://docs.aws.amazon.com/general/latest/gr/rande.html `eu-central-1`). I believe this is referenced as Signagure Version 4 (https://docs.aws.amazon.com/general/latest/gr/sigv4_elements.html).

https://github.com/outline/outline/blob/ffe7b5a41c09ea2dab80f0b9f934499c8e18fbc4/server/utils/s3.js#L33

I believe that using `sha-256`, instead of `sha-1` should fix this issue.

Testing with an S3-bucked on `eu-central-1` fails, using a bucket on `eu-west-1` (Ireland) works.

**Comment by tommoor** [comment] 2019-02-25 18:38
Thanks for reporting! This seems like a duplicate of https://github.com/outline/outline/issues/759 – still happy to land PR's adding support for the new format.

**Closed by tommoor** 2019-02-25 18:38 UTC
