### ISSUE TITLE
User unable to login via SSO after changing email to different domain

### ISSUE THREAD

**Issue by sjthiessen** [outline/outline#7092] opened 2024-06-19 14:07 UTC
We're using Authentik as SSO provider. When changing an users mail adress to a mail **with a different domain**, they won't be able to login again. Error is similar to https://github.com/outline/outline/issues/4668

`{"error":"User authentication aa0cb10e6013efc6d35166b651b76e2e78c6893fd1361b8153643c63ffe782ef already exists for 1021b507-9976-4d43-9afc-61951cd81222, tried to assign to 4cc35fea-5170-4183-b343-e56f303107dc","level":"error","message":"Error during authentication","stack":"Error: User authentication aa0cb10e6013efc6d35166b651b76e2e78c6893fd1361b8153643c63ffe782ef already exists for 1021b507-9976-4d43-9afc-61951cd81222, tried to assign to 4cc35fea-5170-4183-b343-e56f303107dc\n    at userProvisioner (/opt/outline/build/server/commands/userProvisioner.js:55:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:74:12)"}`

**To Reproduce**

1. Have a user set up via SSO and with a connected account in outline
2. Change the mail from `example@provider.com` to `example@differentprovider.com`
3. (Log out and) log in into outline via SSO again

**Expected behavior**
Changing the mail via SSO should not break the login

**Screenshots**
![grafik](https://github.com/outline/outline/assets/74589534/e481a839-453d-438b-a201-d8ee02afadb0)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.76.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 127.0

**Comment by tommoor** [comment] 2024-06-19 21:38
Duplicate of https://github.com/outline/outline/issues/6858 – the best thing you can do is manually update the users email address in the db right now

**Closed by tommoor** 2024-06-19 21:38 UTC
Labels: bug
