### ISSUE TITLE
Upgrade to v0.75.1 requires deprecated field value to be present even if the newer values are populated.

### ISSUE THREAD

**Issue by samstride** [outline/outline#6574] opened 2024-02-21 23:35 UTC
**Upgrading Self Hosted instance**

So we tried upgrading outline from v0.75.0 -> v0.75.1.

The release notes have this info:

```
MAXIMUM_IMPORT_SIZE was deprecated and split into FILE_STORAGE_IMPORT_MAX_SIZE (for documents) and FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE (for workspace imports)
```

As per the documentation here: `https://github.com/outline/outline/blob/main/.env.sample`

we have set the required fields `FILE_STORAGE_IMPORT_MAX_SIZE`, `FILE_STORAGE_UPLOAD_MAX_SIZE` and `FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE`.

However the container complains that `MAXIMUM_IMPORT_SIZE` is missing.

After setting `MAXIMUM_IMPORT_SIZE`, the container starts.

Is this the expected behaviour ?

**Comment by tommoor** [comment] 2024-02-21 23:49
Duplicate of #6571 - this is a bug that will be fixed in the next build

**Closed** 2024-02-21 23:49 UTC
Labels: bug
