### ISSUE TITLE
Preferences / Account / Preferences / Behavior / Separate editing: selection is not saved

### ISSUE THREAD

**Issue by EduNetEurope** [outline/outline#6386] opened 2024-01-14 12:02 UTC
Separate editing is disabled as a workspace feature (Preferences / Workspace / Features).

However, the setting gets overriden by Preferences / Account / Preferences. I can disable the separeted editing mode here too, but the setting is not saved. Whenever I log out / in again, the separte editing mode is enabled again.

**To Reproduce**
1. Make sure separate editing mode is disabled as a workspace feature.
2. Disable it as a account preference.
3. Log out / log in
4. Separated editing mode is unfortunately disabled again.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v.0.74.0

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version [Version 120.0.6099.217 (Offizieller Build) (64-Bit)]

**Comment by tommoor** [comment] 2024-01-14 15:19
This sounds like a duplicate of https://github.com/outline/outline/issues/6329 – if so it will be fixed in the next release, try uploading an avatar

**Closed** 2024-01-19 02:22 UTC
Labels: bug
