### ISSUE TITLE
Opening search result on new tab gives 404

### ISSUE THREAD

**Issue by sekanderb** [outline/outline#7188] opened 2024-07-03 06:45 UTC
**To Reproduce**
1. search for a keyword 
2. open the result on new tab by right clicking on the title.

**Expected behavior**
Open the document 

**Outline:**
- Install: self hosted
- version: 0.77.2

**Desktop**
 - OS: MacOS Sonoma
 - Browser: Chrome

**Comment by tommoor** [comment] 2024-07-03 12:09
I can't reproduce this issue currently, links in search results are just regular links – what is the url of the 404? Do you have more details or screenshots?

**Comment by vikasiwp** [comment] 2024-07-03 13:28
https://github.com/outline/outline/assets/108919165/25be1ce8-50da-4bee-8b5d-cbe91418a03a

**Comment by tommoor** [comment] 2024-07-03 13:32
Interesting, the url is identical so some sort of data loading / permissions race condition perhaps – are there any errors in the developer console? Many thanks

**Comment by vikasiwp** [comment] 2024-07-03 13:34
I believe search indexing is not running somehow, when I share the document it shows the old data saved long ago. 

Also, we recently shifted the wiki from a docker based deployment to a k8s based deployment.

**Comment by tommoor** [comment] 2024-07-03 21:28
Does the document load if you refresh the tab with "Not found" error

**Comment by vikasiwp** [comment] 2024-07-04 01:28
No

- Vikas
Founder, InstaWP.com

**Comment by tommoor** [comment] 2024-07-04 01:29
Interesting, so it's not related to search then – what are the permissions on the collection and the document.

**Comment by vikasiwp** [comment] 2024-07-05 06:30
You are right. 

![CleanShot 2024-07-05 at 12 00 22@2x](https://github.com/outline/outline/assets/108919165/db1786e3-c7ef-4f08-8ee8-62817f6ba8a8)

**Comment by satnamaix** [comment] 2024-07-05 07:14
{"label":"http","level":"info","message":"  <-- GET /doc/onoff-boarding-tech-support-LAt85rPjgE"}
{"label":"http","level":"info","message":"  --> GET /doc/onoff-boarding-tech-support-LAt85rPjgE 200 12ms 1.45kb"}
{"label":"multiplayer","level":"info","message":"Closed connection to \"document.60475b77-bd0b-4729-bc24-5d3735debd6e\"","userId":"f13bd6aa-8bb7-47ac-950c-5a4ef0d900fb"}
{"label":"http","level":"info","message":"  <-- POST /api/auth.info"}
{"label":"http","level":"info","message":"  --> POST /api/auth.info 200 26ms 2.1kb"}
{"label":"worker","level":"info","message":"ValidateSSOAccessTask running","userId":"f13bd6aa-8bb7-47ac-950c-5a4ef0d900fb"}
{"label":"http","level":"info","message":"  <-- POST /api/notifications.list"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.drafts"}
{"label":"http","level":"info","message":"  <-- POST /api/collections.list"}
{"label":"http","level":"info","message":"  <-- POST /api/userMemberships.list"}
{"label":"http","level":"info","message":"  <-- POST /api/stars.list"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.list"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.info"}
{"label":"http","level":"info","message":"  --> POST /api/notifications.list 200 124ms 17.62kb"}
{"label":"http","level":"info","message":"  xxx POST /api/documents.info 404 131ms -"}
{"label":"http","level":"info","message":"  --> POST /api/stars.list 200 163ms 158b"}
{"label":"http","level":"info","message":"  --> POST /api/documents.drafts 200 240ms 7.67kb"}
{"label":"http","level":"info","message":"  --> POST /api/userMemberships.list 200 223ms 6.1kb"}
{"label":"http","level":"info","message":"  --> POST /api/collections.list 200 250ms 17.49kb"}
{"label":"http","level":"info","message":"  --> POST /api/documents.list 200 240ms 147b"}
{"label":"http","level":"info","message":"  <-- GET /static/sw.js"}
{"label":"http","level":"info","message":"  --> GET /static/sw.js 200 5ms 35.31kb"}

This is console error

**Comment by tommoor** [comment] 2024-07-05 12:20
How do you have access to this document, what are the permissions?

**Comment by vikasiwp** [comment] 2024-07-05 12:32
You mean like system permission on the file?

**Comment by tommoor** [comment] 2024-07-05 12:35
No, in Outline. What are the permissions on the collection and the document itself that give you access.

**Comment by vikasiwp** [comment] 2024-07-05 12:39
Everyone can edit. 

Note: I just created a new doc and I can access it by pasting the URL. It works well. Only the old URLs migrated from the older docker based instance are not working.

**Comment by tommoor** [comment] 2024-08-29 16:56
Closing as unreproducible for now

**Closed by tommoor** 2024-08-29 16:56 UTC
Labels: bug, more information needed, self-hosted

**Comment by kerberjg** [comment] 2024-09-28 15:45
Leaving this here for posterity: debugged and fixed in #7589 , turns out this is a DB index corruption issue.

Run `REINDEX TABLE documents;` and it'll be fine ✨

(cc @vikasiwp )
