### ISSUE TITLE
Hitting return on a completed TODO item should create an un-checked TODO item below

### ISSUE THREAD

**Issue by bjj** [outline/outline#4014] opened 2022-08-25 07:57 UTC
**To Reproduce**
1. Create a TODO list
2. Mark some items complete
3. Click on the end of the line of a **completed** item and hit return

**Expected behavior**
A new TODO item inserted below with the cursor ready to type the text associated with the item. The todo item should **not** be checked.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.65.2 tag

**Comment by tommoor** [comment] 2022-08-25 08:04
Duplicate of #3663

**Closed by tommoor** 2022-08-25 08:04 UTC
Labels: bug
