### ISSUE TITLE
Google avatars/profile image disappear after a week

### ISSUE THREAD

**Issue by voxelbee** [outline/outline#3140] opened 2022-02-17 22:55 UTC
We have setup authentication with Google and the profile images are being pulled from Google however after a week the images disappear and become default profile images. The URL that outline references seems to expire after a week.

If you view your profile in outline in `settings -> profile` it will cache your profile image so it doesn't disappear. 

Maybe caching everyone's profile picture when they login is a solution...

**To Reproduce**
1. Log in with google and wait for the profile picture link to expire. This could take a week. **Don't view your profile**

**Expected behavior**
Your profile photo should not disappear.

**Outline:**
- Install: self hosted
- Version: 84cc45e82612771381ae5da12db9c84202406941

**Desktop:**
 - Any

**Mobile:**
 - Any

**Comment by tommoor** [comment] 2022-02-18 02:18
It sounds like the avatar could not be transfered to storage, in which case it would fallback to storing the url from the auth provider. You should check your server logs for `Couldn't upload user avatar image to S3`

**Comment by voxelbee** [comment] 2022-02-18 20:21
It must have failed to transfer to storage at the beginning when people logged in for the first time we had a permissions error with S3 at that time. There are no errors about uploading to S3 anymore and we have tested it that people can upload there own images to their profile.

Could we wipe out the image URLs from the database and then when everyone logs in again it attempts to refetch the images from Google. What would be the correct way to reset that. 

The expected behavior would be that when you log in through Google it fetches your image at that time and replaces the one in outline. This means it would keep the profile pictures synced between Google and outline every time you login.

**Comment by voxelbee** [comment] 2022-02-22 22:43
Ok for now we have gone and changed the URLs manually.

Fetching the image from google every time you log in I think would be beneficial to keep the profiles synced. Maybe there could be a setting to enable or disable permanent syncing of profiles. If that's enabled don't allow people to change the image in Outline if it's being synced with Google?

**Comment by tommoor** [comment] 2022-03-04 01:38
It could be an option for sure. For now I'm going to close this issue as resolved as it was caused by your self hosted configuration problems.

**Closed by tommoor** 2022-03-04 01:38 UTC
Labels: self-hosted
