### ISSUE TITLE
Documents showing old versions

### ISSUE THREAD

**Issue by ghost** [outline/outline#5649] opened 2023-08-04 17:08 UTC
When opening certain documents, an older revision appears instead of the latest one.

**To Reproduce**
1. Go to pages for specific documents

**Expected behavior**
The latest revision is displayed.

Below is a view of the latest revision:
![rev](https://github.com/outline/outline/assets/105711348/cbfc6cdd-9bc3-4fbf-a40f-637010fdb371)

While below is a view of the document, after closing the history panel. Note how it differs from the latest revision:
![doc](https://github.com/outline/outline/assets/105711348/90eee18b-36ab-4487-96df-56d0a89ea5d6)

**Outline:**
- Install: self-hosted
- Version: v0.70.2

**Desktop:**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 115.0.5790.171

**More details**
1. The correct version of the document flashes briefly while the page is loading, but it is quickly replaced by what appears to be an older version.
2. This happened right after upgrading our self-hosted outline to the latest version.

**Comment by yacir** [comment] 2023-08-07 07:43
Related to #5621. 
The correct version of some documents flashes briefly while the page is loading, but it is quickly replaced by what appears to be an older version. But for some others the correct version of some documents flashes briefly without beeing replaced so we ended with an empty page

**Comment by tommoor** [comment] 2023-08-07 12:22
Nothing really changed in v0.70.0 that would map to this, what version was being upgraded from?

**Comment by yacir** [comment] 2023-08-07 12:51
@tommoor in my case was from `0.68.1` to `0.70.1`

**Comment by tommoor** [comment] 2023-08-07 13:00
Is the collaboration websocket connecting correctly? You'd be able to see in the browser console. Should also check for errors both there and in the server logs.

**Comment by tm-pepe-bawagan** [comment] 2023-08-09 06:22
We have collaborative editing turned off.

**Comment by tm-pepe-bawagan** [comment] 2023-08-09 06:24
in our case it was also from `0.68.1`

**Comment by yacir** [comment] 2023-10-06 18:01
@tommoor I rollaback to 0.68.1 and all went well - the documents displayed with the correct version. 
I then tried to upgrade to 0.69.2 this time and had the problem again.

**Comment by tommoor** [comment] 2023-10-06 18:12
You can try removing the inbrowser cache and see if that helps, search for this command in `cmd`+`k`.

<img width="770" alt="image" src="https://github.com/outline/outline/assets/380914/f4d218df-2b4f-4282-934e-3701d645b1f3">

**Comment by tm-pepe-bawagan** [comment] 2023-10-09 05:53
> You can try removing the inbrowser cache and see if that helps, search for this command in `cmd`+`k`, run it and reload.
> 
> <img alt="image" width="770" src="https://user-images.githubusercontent.com/380914/273298535-f4d218df-2b4f-4282-934e-3701d645b1f3.png">

this did not solve the problem

**Comment by yacir** [comment] 2023-10-09 08:33
@tommoor  I don't think it's a client-side problem, since I'm not the only one in the team who's had to deal with it. What's more, these are documents I've never opened before.

**Comment by wasdennnoch** [comment] 2023-10-10 08:31
We're experiencing this issue with a document that is occasionally synced with an external service using the API (`documents.update` on v0.71.0, collaborative editing enabled). The most recent changes often only appear in the document history, but not in the document itself.

- Looking at DevTools, the initial `documents.info` call _does_ return the up to date version.  
- For some reason, this document often reaches "the maximum number of connections" \*, so the collaborative Websocket can't connect. If this is the case, Outline appears to fall back to a locally cached, likely oudated version of the document instead of the up to date version that was just fetched using `documents.info`. Clearing the IndexedDB cache _does_ restore the latest document state.

I _think_ I also once saw the collaborative socket returning an outdated version of the document, but I can't double-check that since, well, it's currently at the max number of connections for some reason.

I've done some more experimentation on my own Outline instance (v0.72.1, collaboraitve editing enabled, using an API token assigned to my own user account) and found:

- Using `documents.update` to update a document's text doesn't fire any event through the collaborative websocket. It _does_ fire an event though the "normal" socket.io WS, but this doesn't visually update the document to the latest state while the doc is open. The "last updated at" text _is_ immediately updated though.
  - Reloading the tab briefly flashes the updated version and then reverts to the previous version. Just to revert back to the updated version a bit later, once the collaborative socket connects and sends the latest diff.
  - Tying this into the above: If the collaborative socket fails to connect, the outdated version keeps being displayed, even though the client should already know the latest state due to `documents.info`.

All of those things seem to related to client behavior though and don't fully explain everything that other people have mentioned in this issue. It does seem to be part of the issue though. Overall it seems that collborative editing doesn't play nicely with "non-collaborative" api actions.

\* I don't know if this is caused by a bad proxy configuration on our side or if it is a bug in the Outline API; for now I'll ignore the root cause and instead focus on outdated documents being displayed. No, we definitely don't have 100 people looking at the document at the same time.

---

Not sure if this is related to this issue, but I've also managed to "lose" changes of a document revision, by repeatedly (~120 times) updating a document using `documents.update` (at a rate of about twice per second, so while it _could_ be a race condition, it _should_ be slow enough not to be one?). The document returned in Insomnia had the revision 126. Fetching the same document again using `documents.info` also had the revision 126, but _without_ the latest changes to the text; instead, the text was from an older revision. The History also didn't contain the change. I don't quite know from which revision the returned state was, because I didn't actually change the text each update, I just hit the send request button repeatedly and only changed the text during the last update, i.e. the change that got lost.

**Comment by checkraisefold** [comment] 2023-10-13 06:09
I took a look in DBeaver at the DB after making some documents.
![image](https://github.com/outline/outline/assets/19525688/a45b127a-1fe5-4392-acd7-57ae0df1bce0)
Not actually saving the text to the DB, but only shows in cache in the browser. Still somehow there after I clear IndexedDB cache. Very cool!

**Comment by iljoja** [comment] 2023-11-02 18:23
We have exactly the same problem migrating from 0.68.0 to any newer version. Please let us know if we can assist in any way to solve this.

**Comment by chkal** [comment] 2024-02-23 07:33
I'm seeing the same issue. Clearing the site data of the browser seems to fix the issue for me. We are using v0.75.0.

**Comment by Lowaiz** [comment] 2024-05-14 13:36
Hello everyone,

We may have found the source reason of this, but we are getting stuck on a solution that does not suit us very well, so any help/remarks would be a blessing :

In early 2023, we did a test of the Collaborative Edition feature, but the feedback was a bit mitigated as users were a bit confused to be several users to edit a doc, so we decided to disable the feature.

That resulted into a `Documents` table containing, for some documents, non-null `state` column.

Fast forward to the 0.69.0 bump, the collaborative edition seems be enforced from now on, as the code related to the check of team's `collaborativeEditing` property inside the Multiplayer Editor has been removed.

Now begin problems:
On every document that were editing during our test of the collaborative editing, where the state column is not NULL, [the collaborative websocket send a Y-Doc derivated from this `state` column](https://github.com/outline/outline/blob/main/server/collaboration/PersistenceExtension.ts#L47), column that wasn't updated in months. Resulting in the front app to first load the correct version issued from the `documents.info` API call, then received and load the version sent by the socket.

From here, we can set the whole `state` column to NULL to fix the problem, and the app will refresh this state column for every document that will be edited in the future.

But now begin problems V2:
After the upgrade, if a user visit the page of a doc, while having a version of the document stored inside IndexedDB, the editor, even outside of the edit mode, will append the cached version to the displayed doc AND automatically push the change to the server.

We arrived at the limit of our debug (more than 25 hours spent in total for both bugs), and to fix this IndexedDB problem we can't think other things than changing the domain name of our instances, to avoid any problem with the previous versions stored in local or fork and remove the IndexedDB feature, as we don't real care about performance or offline edit.
Both of these solutions seems really overkill for 4 lines of code. 

Maybe a feature to enable/disable the local storage/indexedDB could be a great solution.

**Comment by tommoor** [comment] 2024-05-14 15:52
Hi @Lowaiz – this sounds very plausible based on the way everything works. And this was one of the reasons that storage of the collaborative state was enforced from v0.69.0 onwards. 

> Maybe a feature to enable/disable the local storage/indexedDB could be a great solution.

It doesn't make sense to introduce a configuration here, this change is very old from the projects perspective and outside of the bug you're seeing there is no downside to iDB that would be visible to the end user justifying configuration.

> to fix this IndexedDB problem we can't think other things than changing the domain name of our instances

Changing the domain would work, you can also have everyone on your team clear their local data for Outline, either through the browser controls or using the "Clear IndexedDB cache" command that's available in the command menu (`cmd`+`k`).

**Closed by tommoor** 2024-05-14 15:52 UTC
Labels: bug, more information needed, self-hosted

**Comment by wh1te909** [comment] 2024-05-14 22:01
It doesn't just affect older versions that upgraded, I've got the same issue and only discovered Outline a few weeks ago, so I have only ever used version 0.75.2. Have not upgraded to version 0.76.1 yet so not sure if this was already fixed in that update.

Tried all the fixes here but still never manged to recover data for some documents, ended up having to restore from one of my daily postgres dumps to get the data back.

**Comment by Solvik** [comment] 2024-07-24 16:53
@tommoor, changing the domain for a tool used for internal documentation is challenging and somewhat counterproductive. I would like to avoid this if possible. It would require us to update every link that points to our current Outline instance, which would involve a significant amount of collateral work.

Additionally, asking hundreds of users to clear their IndexedDB cache after login is complex. Some users might not know how to do this or might forget, leading to them accessing outdated or incorrect data.

Do you have a better solution? It seems like this issue affects more than just a few people with their self-hosted Outline instances.

We would be happy to contribute to resolving this issue and help those who are stuck with a 1.5-year-old, non-updated version. However, we would need your guidance on how to best approach this.

**Comment by tommoor** [comment] 2024-07-27 00:44
@Solvik this is only an issue of you enabled and then disabled the multiplayer option all that time ago. Do you think that's the case here?

**Comment by tommoor** [comment] 2024-08-21 16:08
I'm not sure what you mean by sustainable over time - you would only need to do this once for each client and then it's done. You can go back to the standard image.

**Comment by marianne-butaye** [comment] 2024-10-29 11:26
Hello, is there any news on the resolution of this bugfix ?

I also had it on Outline SaaS.

For me, it seems to only happen when using the API (documents.update) : when looking at the updated document via API, document update date & author are up to date, with latest revision first flashing by quickly and then the content shows another older revision (not the latest one). 

When you look in the history mode, the current revision is said to be the latest one, but its content when selected is not the same as when history mode is closed (so the revision selected is in fact not the latest one) -> but outline thinks the current revision is the latest one, so you cannot restore it to the latest revision either. 
So the best workaround for the moment for us is to delete and re-create the document (but we lose the history feature and the url of the document also changes).

I don't have the problem when updating a document manually (not via API), even if document was created via API.
