### ISSUE TITLE
Title in side bar isn't updating after title change

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1508] opened 2020-09-02 14:28 UTC
**To Reproduce**
1. Rename a document
2. Refresh
3. See error

**Expected behavior**
Name updated in sidebar

**Screenshots**
![image](https://user-images.githubusercontent.com/23284276/91996082-f9883600-ed0e-11ea-8cce-4ffc74e0a3b6.png)

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.46.1

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version Latest

**Comment by tommoor** [comment] 2020-09-03 03:37
I've been unable to reproduce following these steps, but it'd be a bad bug if the title cache in the collections got out of sync.

**Comment by melikesofta** [comment] 2020-09-03 09:37
I have the same issue, v0.46.1, self-hosted. Client is MacOS chrome

**Comment by pariola** [comment] 2020-09-07 11:40
Same issue here on v0.46.1, self-hosted. Browser: Chrome MacOS

**Comment by tommoor** [comment] 2020-09-07 20:41
Fix will be released in `v0.47.0` within 24h.

**Closed** 2020-09-07 20:41 UTC
Labels: bug, self-hosted
