### ISSUE TITLE
Add @mention recognition to editor

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#2929] opened 2022-01-11 21:09 UTC
in many collaborative text editors, typing @nameofperson is semantically understood as referring to a user. for example in github @tommoor refers to the maintainer of this project.

**Comment by thenanyu** [comment] 2022-01-11 21:10
similarly, date recognition is nice to have with a command like `/today`

**Comment by disambiguationuk** [comment] 2022-01-19 10:47
Pretty much the number one pain we have with outline right now

**Comment by michaelkarrer81** [comment] 2022-01-20 15:06
This would be very much needed!

**Comment by jlqd** [comment] 2022-09-23 14:35
Yes, this is very much desired!

**Comment by james-freec** [comment] 2022-11-18 04:13
one of reason to stop us use getoutline and move from notion to getoutline

**Comment by tommoor** [comment] 2022-11-28 02:55
## Sub-tasks

- [x] User search endpoint `users.list` with `query`.
- [ ] Add inline node `mention_user`, it will store the `id` and `name` in attributes, be a `span` and have `atom: true` set.
- [ ] Add popover triggered by `@` symbol which searches through users and inserts a mention node.
- [ ] Add `MentionsProcessor`, similar to `BacklinksProcessor` that parses which mentions have been added on `"documents.publish"` and `"documents.update"` events.
- [ ] Add notification email for mentions scheduled from `MentionsProcessor`

**Comment by tommoor** [comment] 2023-01-31 02:18
Closing as duplicate of #889

**Closed by tommoor** 2023-01-31 02:18 UTC
Labels: feature, pinned
