### ISSUE TITLE
Error exporting zip - XMLParserError: Unexpected close tag

### ISSUE THREAD

**Issue by stevenb9** [outline/outline#3971] opened 2022-08-15 10:25 UTC
**To Reproduce**
- When exporting I get the following error, I spent weeks trying to find the root cause to no avail, I'm running in docker.

`{"error":"Unexpected close tag\nLine: 5\nColumn: 7\nChar: >","stack":"XMLParserError: Unexpected close tag\nLine: 5\nColumn: 7\nChar: >\n    at error (/opt/outline/node_modules/sax/lib/sax.js:651:10)\n    at strictFail (/opt/outline/node_modules/sax/lib/sax.js:677:7)\n    at closeTag (/opt/outline/node_modules/sax/lib/sax.js:871:9)\n    at SAXParser.write (/opt/outline/node_modules/sax/lib/sax.js:1436:13)\n    at Parser.exports.Parser.Parser.parseString (/opt/outline/node_modules/xml2js/lib/parser.js:322:31)\n    at Parser.parseString (/opt/outline/node_modules/xml2js/lib/parser.js:5:59)\n    at NodeXmlParser.parse (/opt/outline/node_modules/aws-sdk/lib/xml/node_parser.js:31:10)\n    at Request.extractError (/opt/outline/node_modules/aws-sdk/lib/services/s3.js:696:39)\n    at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:686:14)\n    at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:688:12)\n    at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:686:14)\n    at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10","level":"error","message":"Error processing task in ExportMarkdownZipTask"}`

**Screenshots**
![Screenshot 2022-08-15 at 12 24 21](https://user-images.githubusercontent.com/24360476/184619320-2bbef6fd-28ff-4ee8-aca9-5b0a545ef055.png)

**Outline (please complete the following information):**
- Install: [self hosted, Docker]
- Version: [0.65.2 release]

**Comment by tommoor** [comment] 2022-08-15 21:27
Duplicate of #3209

**Closed by tommoor** 2022-08-15 21:27 UTC
Labels: bug
