### ISSUE TITLE
Error when attempting to create link from dropdown when editing (both new and updating) documents 

### ISSUE THREAD

**Issue by jlb-qi** [outline/outline#1455] opened 2020-08-14 12:37 UTC
I'm trying to add a link to a new document and I get the following error.

```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

**To Reproduce**
1. Create a new document
2. Use `/` to open the options menu.  
3. Click on `Link`
4. See error (as described above)

**Expected behavior**
I expect to be given the option to add a internal/hyperlink along with a name for it.

**Outline (please complete the following information):**
- Install: self-hosted, development setup in docker
- Version: 174acfac32e19c5d7dc5a428955bd1b45d10fabe

**Desktop (please complete the following information):**
 - OS: Macbook Pro 2019
 - Browser: Chrome
 - Version: 84.0.4147.105

**Comment by MatheusRV** [comment] 2020-08-14 14:16
Seems related to: https://github.com/outline/rich-markdown-editor/issues/208

Try use other browser..

**Comment by jlb-qi** [comment] 2020-08-14 14:55
Interestingly, when I perform the same action but with the Console Inspector open, the error does not appear

**Comment by tommoor** [comment] 2020-08-14 22:57
Thanks for filing, this is a duplicate of #1426 – It makes sense that it would not reproduce with console open as the loop is in some way a function of window sizing

**Closed by tommoor** 2020-08-14 22:57 UTC
Labels: bug

**Comment by jlb-qi** [comment] 2020-08-17 12:37
Ah makes sense. Thanks for the quick response 🙏
