### ISSUE TITLE
Feature: A comment must be able to be closed

### ISSUE THREAD

**Issue by LudovicGodart** [outline/outline#6405] opened 2024-01-18 15:05 UTC
**Feature request**
The current commenting system is unusable for a team.
It does not allow feedback on a document shared within a team. Having processed a comment, it should be possible to move it to “resolved” status.

This makes it easier to monitor the remaining comments that have not yet been processed.
Why not provide a place to find “archived” comments.

I think you should take inspiration from what Google Doc does at this level, because it is not really collaborative at the moment.

N.B: Wrong label, can't change it to feature.

**Comment by tommoor** [comment] 2024-01-18 15:09
Duplicate of https://github.com/outline/outline/issues/5078

**Closed by tommoor** 2024-01-18 15:09 UTC
Labels: bug
