### ISSUE TITLE
Type of notice box cannot be changed via the drop-down

### ISSUE THREAD

**Issue by saschawx28** [outline/outline#4137] opened 2022-09-19 06:47 UTC
The type (info, warning, error) of a notice box cannot be changed via the drop-down menu on the right side of the box.

**To Reproduce**
1. Insert a notice info box
2. Change the type of notice box using the drop-down menu on the right-hand side
3. The type does not change

**Screenshots**
<img width="828" alt="notice-box-type" src="https://user-images.githubusercontent.com/31009088/190961998-6a43bc60-4a47-46c2-b1ca-7f5b22a25dfb.png">

**Outline (please complete the following information):**
- Install: both, getoutline.com and self hosted
- Version: v0.66.0

**Desktop (please complete the following information):**
 - OS: macOS, Linux
 - Browser: Chrome
 - Version: latest stable

**Comment by saschawx28** [comment] 2022-09-22 08:39
Tested with Safari and Firefox, both on macOS, and it works as expected. It seems to be a Chrome-only problem.

**Comment by tommoor** [comment] 2022-09-23 01:30
Unfortunately I'm not able to reproduce, any errors?

**Comment by saschawx28** [comment] 2022-09-23 09:00
I'm not sure why this didn't work, but in a Chrome incognito window it does. I reset my Chrome profile and now it works as expected. I close this and sorry for the noise.

**Comment by kucaiyi** [comment] 2023-02-18 19:01
I am experiencing a similar issue: I cannot change the type of the code block and cannot scroll the content horizontally. It seems like the code block keeps resetting.
My main browser is Chrome. I just tested on Chrome Incognito and Safari, and it works as expected. I am not sure if it is a browser-specific issue.

**Comment by saschawx28** [comment] 2023-04-25 07:38
The issue still exists in 0.68.1 and Chrome 112.

**Comment by tommoor** [comment] 2023-04-25 18:46
Most likely a browser extension such as grammarly is causing the issue if it works in Incognito

**Comment by tommoor** [comment] 2023-05-26 02:30
should be fixed by https://github.com/outline/outline/pull/5366

**Closed by tommoor** 2023-05-26 02:30 UTC
Labels: bug, editor, more information needed, self-hosted

**Comment by saschawx28** [comment] 2023-05-26 06:44
Good to hear. I will give it a try when it is released.

**Comment by tommoor** [comment] 2023-08-01 14:14
The dropdown was removed on purpose recently, it may get restored but for now you need to create another notice type separately.
