### ISSUE TITLE
Share links display 404

### ISSUE THREAD

**Issue by simonokeefe** [outline/outline#1344] opened 2020-07-12 03:08 UTC
Clicking on any public share link displays "404 | This page could not be found."

Example (failing as at 2020-07-12): https://www.getoutline.com/share/fd65ca7b-cc5b-486f-9ce0-61c98693c301

![image](https://user-images.githubusercontent.com/3085124/87237916-566a1d00-c43f-11ea-9162-93e53f05376f.png)

**Comment by tommoor** [comment] 2020-07-12 03:34
Thanks for filing, looking into a fix for this now – we deployed a new marketing site today that was the cause of this.

**Comment by tommoor** [comment] 2020-07-12 04:44
Thanks again, all resolved.

**Closed by tommoor** 2020-07-12 04:44 UTC
Labels: bug
