### ISSUE TITLE
Timeout Error when trying to import Notion content

### ISSUE THREAD

**Issue by cgrard** [outline/outline#4006] opened 2022-08-24 10:19 UTC
Hi there,

I'm hosting a brand new Outline application from a minimal Ubuntu headless box using Docker, I'm running the latest available image which is outlinewiki/outline:0.65.2, my S3 storage is provided using minio, both S3 and app are served behind a reverse proxy and everything seems to be working properly : I can upload images, they display properly, I can publicly share a page with images in it and they show properly as well.

However when I try to import content from Notion, uploading the zip file works properly and then it processes for about 10 minutes before saying "Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?".
I've try to repack the ZIP, put less content in it and even put very simple text just to see if it's indeed a content issue but it still does not work.

When I look into the application logs I can see this : 
```
outline-docker-outline-1  | {"error":"connect ETIMEDOUT 111.222.333.444:443","stack":"Error: connect ETIMEDOUT 111.222.333.444:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)","level":"error","message":"Error getting file from S3 by key"}
outline-docker-outline-1  | {"label":"task","level":"info","message":"ImportTask parsing data for 5c024027-dfdc-4005-a6a8-fa9cf0d272c1"}
outline-docker-outline-1  | {"error":"Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?","stack":"Error: Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?\n    at /opt/outline/node_modules/jszip/lib/utils.js:454:17\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ImportNotionTask.parseData (/opt/outline/build/server/queues/tasks/ImportNotionTask.js:44:17)\n    at async ImportNotionTask.perform (/opt/outline/build/server/queues/tasks/ImportTask.js:52:22)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:132:7)","level":"error","message":"Error processing task in ImportNotionTask"}
```
As you can see there's a timeout on my public IP address (that is redacted here) which is odd because it appears nowhere as is in my configuration, and if the app is really trying to access the S3 bucket using the raw IP address it will fail no matter what because everything is behind a reverse proxy.

Is this a known or wanted behavior? Is there anything I can check or look at to fix this on my side?

**Comment by tommoor** [comment] 2022-08-24 10:21
Seems like a duplicate of https://github.com/outline/outline/issues/3829 – how big is the file?

**Comment by cgrard** [comment] 2022-08-24 10:22
I've tried different scenarios up to a single page with minimal content, the last one I've tried is 6.4kb

**Comment by tommoor** [comment] 2022-08-24 10:24
Gotcha. You can see it timedout trying to access the file from Minio – so in some way it's a problem with your deployment configuration, beyond that it's difficult to say.

**Comment by cgrard** [comment] 2022-08-24 10:27
But if indeed is a S3 configuration issue, then all the uploads should be impacted (images, avatars, etc) right?

**Comment by tommoor** [comment] 2022-08-24 10:36
I suppose the clue is that this is one of the few spots where the file is downloaded on the server-side.

I retracted my previous comment about it being config although tweaking some configuration may help. You believe the Ip address it's hitting is aws?

**Comment by cgrard** [comment] 2022-08-24 10:39
Yes, the IP is my public IP address that is behind the domain.tld :
Here is my docker-compose AWS part configuration for the outline container:
```
      - AWS_ACCESS_KEY_ID=minio
      - AWS_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=<redacted>
      - AWS_S3_UPLOAD_BUCKET_URL=https://s3.domain.tld
      - AWS_S3_UPLOAD_BUCKET_NAME=outline
      - AWS_S3_UPLOAD_MAX_SIZE=26214400
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private
```
and here is the minio part:
```
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=<redacted>
      - MINIO_BROWSER_REDIRECT_URL=http://s3:9001 #internal only, not exposed
```
In minio I have only one bucket called "outline" and I can see the uploads (including the Notion export ZIP files) in the 'uploads' folder. DNS resolution looks OK to me as it is indeed the IP that is set for this particular domain.tld but I'll check again.

**Comment by cgrard** [comment] 2022-08-24 11:16
OK there's something new. I thought about what you said about DNS resolution and remembered that I already encountered a similar issue with a totally different application and it was network related, basically I forced the resolution for s3.domain.tld so the corresponding IP would be the internal reverse proxy IP instead of the public one, and the error has now changed.

When I import the ZIP it now fails almost immediately with a "Uploaded file does not contain any valid documents" error :

```
outline-docker-outline-1  | {"label":"task","level":"info","message":"ImportTask fetching data for 0d38310f-59db-4835-85b3-9009665d7af5"}
outline-docker-outline-1  | {"label":"task","level":"info","message":"ImportTask parsing data for 0d38310f-59db-4835-85b3-9009665d7af5"}
outline-docker-outline-1  | {"error":"Uploaded file does not contain any valid documents","stack":"BadRequestError: Uploaded file does not contain any valid documents\n    at ValidationError (/opt/outline/build/server/errors.js:95:34)\n    at ImportNotionTask.perform (/opt/outline/build/server/queues/tasks/ImportTask.js:59:43)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:132:7)","level":"error","message":"Error processing task in ImportNotionTask"}
```

**Comment by tommoor** [comment] 2022-08-24 11:21
Can you screenshot the internal zip folder structure

**Comment by cgrard** [comment] 2022-08-24 11:24
Sure, really nothing fancy about it but here it is: 

![image](https://user-images.githubusercontent.com/59442629/186406636-b6a5f71f-4acf-4d83-825d-f854e4c90d19.png)

**Comment by tommoor** [comment] 2022-08-24 11:26
Yea, for a single HTML file you can just import directly or drag and drop – the tool is designed for importing a full export from Notion, see the instructions on the import process.

Closing out as there being no bug for us to fix here, feel free to continue comments.

**Closed by tommoor** 2022-08-24 11:26 UTC
Labels: bug, more information needed, self-hosted

**Comment by cgrard** [comment] 2022-08-24 11:30
Indeed, I tried with the much bigger archive I had and it worked like a charm! Thanks man! The support on this project is amazing!

**Comment by RomanMazyrin** [comment] 2022-09-01 14:36
@cgrard Hi mate! Could you tell me please how did you solve your problem with DNS resolution? I have the same error with "connect ETIMEDOUT 111.222.333.444:443"

**Comment by cgrard** [comment] 2022-09-01 14:44
I simply added a line in /etc/hosts to force the domain to match my reverse proxy internal IP address instead of the public one, but it may very well be another issue in your.
