### ISSUE TITLE
todo list checkbox consistency issue

### ISSUE THREAD

**Issue by Snuupy** [outline/outline#2179] opened 2021-06-05 07:12 UTC
# Description: 
Checking and unchecking an item in the todo list leads to a consistency error in the front-end (but not the back-end).

**To Reproduce**
1. Create a todo list with 2 (or more) items
2. Check the first item
3. Check the first item again
4. See that *BOTH* the first and second item are now checked (although the second one doesn't have the strikethrough, and if you refresh now the 2nd item is not actually marked as completed in the backend)

**Expected behavior**

Only the first item should be checked. This is a bug introduced in v0.56 (was working fine in v0.55).

**Screenshots**

Recording: https://giant.gfycat.com/FlakyNeedyGnu.mp4

**Outline (please complete the following information):**
- Install: self hosted
- Version: 9817e2f

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: chrome lastest
 - Version: 91.0.4472.77 (Official Build) (64-bit) (cohort: Stable)

**Comment by tommoor** [comment] 2021-06-05 17:17
Could this be a speed thing with toggling the items in quick succession?

**Comment by Snuupy** [comment] 2021-06-17 09:03
another example: 

https://user-images.githubusercontent.com/964538/122366150-4bf6b400-cf29-11eb-9148-b1b2daed6683.mp4

**Comment by tommoor** [comment] 2021-06-17 15:37
I'm still pretty lost as to what's causing this, but it's on deck to fix for this release.

**Comment by Snuupy** [comment] 2021-06-17 23:16
Was just wondering if anyone else was able to reproduce this or if I was the only one.

I don't have another SSL instance set up right now (and slack will only allow SSL callback URLs) so I can't test on another instance yet.

**Comment by tommoor** [comment] 2021-06-18 04:08
I can reproduce, but I cannot reproduce in the [standalone editor](https://github.com/outline/rich-markdown-editor) – so that's particularly weird.

**Closed** 2021-06-18 05:58 UTC
Labels: bug
