### ISSUE TITLE
Team logo & avatar src URLs don't update after a change of `AWS_S3_UPLOAD_BUCKET_URL`

### ISSUE THREAD

**Issue by DrJume** [outline/outline#2246] opened 2021-06-23 02:50 UTC
After changing `AWS_S3_UPLOAD_BUCKET_URL` to a new domain, the src URLs of the logo in the top left and the member overview inside settings are still using the old domain and thus throwing a lot of HTTP 404's.

(I  restarted outline and even cleared the frontends browser data)

**To Reproduce**
1. Setup Outline with a self hosted *AWS S3* with *minio*
2. Login with Slack/ let users join Outline through Slack
3. Transfer *minio* instance to a different domain
4. Update `AWS_S3_UPLOAD_BUCKET_URL` to the new domain
5. Logo and member avatars are missing/not loading (404). These are still using the old domain.

**Expected behavior**
Logo and member avatars are fetched over the newly updated `AWS_S3_UPLOAD_BUCKET_URL`.

**Outline:**
- Install: self hosted
- Version: `v0.56.0`

**Comment by tommoor** [comment] 2021-06-23 16:05
Hi, the fully qualified url is stored in the database – this is by design. You can manually update it to point to your new AWS bucket location though easy enough. You should also find that image attachments are also broken without updating the records in the db?

**Comment by tiagocamargo** [comment] 2021-06-25 10:56
Hi!
I'm in the same situation.
Would using a regular expression to change all URLs directly be feasible?

**Comment by tommoor** [comment] 2021-06-25 16:14
Absolutely, you could write a query to update all of the urls in the db

**Comment by tommoor** [comment] 2021-07-09 12:16
I'm going to close this out as expected behavior as these URL's are stored in the database. If either of you do end up writing a script to migrate data it would be great to share it here for anyone in the future that needs to move storage location

**Closed by tommoor** 2021-07-09 12:16 UTC
Labels: self-hosted

**Comment by DrJume** [comment] 2021-07-27 13:14
I updated the URLs in the Postgres database. But the changes are still not showing in the frontend. Maybe due to the redis cache still giving the wrong URLs?

**Comment by tommoor** [comment] 2021-07-27 13:42
There isn't any redis caching to speak of, there is some local cache in the browser but just loading the app would refresh that (certainly clearing the website cache would).

Where did you update the urls? I would expect to update `avatarUrl` in both the `users` table and the `teams` table

**Comment by DrJume** [comment] 2021-07-27 14:15
I didn't see that the `users` and `teams` table also have urls. I only updated the `attachments` table. 
Now I also updated the `avatarUrl`s and it looks good. 

Thank you!
