### ISSUE TITLE
Editing of favorite documents is not allowed by default

### ISSUE THREAD

**Issue by soulteary** [outline/outline#2308] opened 2021-07-11 06:00 UTC
**To Reproduce**

1. Go to `/starred`
2. Click on 'any document'
3. The `Action Buttons` not initialized at the top, eg: editor.
4. Refresh the page, the buttons is displayed normally.

**Expected behavior**

If the user has editing permissions for this document, no matter where the document is opened from, they should have editing permissions and show the edit button.

------

reproduce steps （version: 0.57.0 with docker）

**Click the Favorites function from the sidebar to enter the page**

![image](https://user-images.githubusercontent.com/1500781/125268163-02d42d00-e33a-11eb-8f5c-fffb4c865b59.png)

**Just click on a document to enter the page, you can see that there is no action button in the upper right corner**

![image](https://user-images.githubusercontent.com/1500781/125268307-28f9cd00-e33a-11eb-803c-147d86386848.png)

**Refresh the page, the operation button appears**

![image](https://user-images.githubusercontent.com/1500781/125268439-4a5ab900-e33a-11eb-8b67-7d2bcf3299e3.png)

**Comment by tommoor** [comment] 2021-07-11 12:47
I cannot reproduce this – which version of the application are you looking at? Please use the bug template.

**Comment by soulteary** [comment] 2021-07-12 09:57
> I cannot reproduce this – which version of the application are you looking at? Please use the bug template.

Sorry, I added the reproduce information below the post dividing line @tommoor

**Comment by tommoor** [comment] 2021-07-12 16:31
Weird, this doesn't reproduce for me on getoutline.com so marking as `self-hosted` issue. It would suggest that the policies are not being returned in the response when loading documents from /starred route.

**Comment by soulteary** [comment] 2021-07-16 23:31
> Weird, this doesn't reproduce for me on getoutline.com so marking as `self-hosted` issue. It would suggest that the policies are not being returned in the response when loading documents from /starred route.

Thanks for the reply, I think it is possible, I will continue to observe later.
During a week of use, I found that outline performs very well in most cases during normal use.

The following are the problems I found during my recent experience, many of which I have solved:

- [x] The program does not support non-picture attachments embedded in documents by default.
- [x] The program's default Chinese language support is incomplete, some entries are not accurate, and front-end elements such as picture titles are not in the language file. The current default Chinese language level is about 70%.
- [x] The program does not provide privatized deployment authentication implementation by default, and does not support whitelisting and associated private OAuth / LDAP authorization.
- [x] The program will grab the user's avatar when it is launched for the first time, which takes a long time when overseas resources are involved.
- [ ] Open a document from favorites, it is not editable by default, you need to refresh to see the button.
- [ ] The program does not set the shortcut keys of "Add Subdocument" and "Add Document at the Same Level", which is not friendly to the early experience of organizing documents.
- [ ] [50%] Currently, there are fewer types of inserted code supported, and the default value is not recorded. By default, JavaScript will be used as the default type.
- [ ] There are problems with the parsing of copy and pasted content styles, and the handling of Markdown and simple style content is acceptable.
- [ ] It is up to the user to choose whether to display the content in embed mode.
- [ ] After the document is moved, the content cannot be modified, it needs to be refreshed first.
- [ ] There is a problem with the parsing logic of the editor, and there are problems with the bold priority or regularity. If there are Chinese symbols in the asterisk, the parsing will be abnormal.

Maybe there are some that can be a reference for the next interactive optimization?

Finally, thank you for developing such a useful knowledge management software. I have recommended it to my friends around me. Maybe I will post a detailed blog on privatization deployment and use later.

**Comment by tommoor** [comment] 2021-07-16 23:38
Great list, some of these are definitely fixed in `v0.58.0` already. Any help you can provide in terms of Chinese language support is greatly appreciated. No one on the maintaining team has native Chinese language skills currently.

Additional translations and fixes can be made on our portal too: https://translate.getoutline.com

**Comment by soulteary** [comment] 2021-07-16 23:48
> Great list, some of these are definitely fixed in `v0.58.0` already. Any help you can provide in terms of Chinese language support is greatly appreciated. No one on the maintaining team has native Chinese language skills currently.
> 
> Additional translations and fixes can be made on our portal too: https://translate.getoutline.com

I will continue to pay attention to and update these contents.
#1881 Privatization deployment In this post, I mentioned some problems and concerns, maybe you can take a look?

Thanks.

**Comment by tommoor** [comment] 2021-08-24 06:36
I'm closing this out as we've never been able to reproduce it outside of your self-hosted environment which it sounds like has been customized heavily.

**Closed by tommoor** 2021-08-24 06:36 UTC
Labels: bug, self-hosted
