### ISSUE TITLE
Animated Gifs showing as single image 

### ISSUE THREAD

**Issue by bglidwell** [outline/outline#2115] opened 2021-05-04 21:34 UTC
**To Reproduce**
1. Add animated gif to content
2. View gif and see it is not animated

**Expected behavior**
Gif should load and animate 

**Outline (please complete the following information):**
- Install: getoutline.com

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 90.0.818.46

**Comment by tommoor** [comment] 2021-05-05 02:11
Hi @bglidwell – I'm not able to reproduce, with gifs in general I recommend downloading the file to your desktop and then insert from there, rather than copy/paste. It seems like a lot of browsers have the behavior of only copying a single frame from the gif when you do this, could be what's happening here?

**Comment by bglidwell** [comment] 2021-05-05 03:37
@tommoor you are absolutely right. I apologize for not checking that first. It was a copy paste issue specific to Edge it seems, as it worked fine with Chrome. I was able to get gifs to add correctly using the method you suggested. Thanks for the quick reply!

**Comment by tommoor** [comment] 2021-05-05 03:45
Okay, great – closing this out

**Closed by tommoor** 2021-05-05 03:45 UTC
Labels: bug, editor
