### ISSUE TITLE
the bold text appears as **text** on the reading page

### ISSUE THREAD

**Issue by jochne** [outline/outline#6683] opened 2024-03-18 08:11 UTC
Bug Report:

Bug Description:
In a Chinese language environment, while using Outline self-hosted version 0.75.2, when a sentence includes text formatted in bold within the editor, this formatting does not carry over to the shared reading page. Instead, the bold text appears as `**text**` on the reading page.

To Reproduce:

1. Access the Outline self-hosted platform (version 0.75.2).
2. Create or edit an article containing a sentence with Chinese characters in bold format.
3. Save the changes and preview or share the article to view the read-only version.
4. Notice how the bold formatting is not preserved; it's displayed as `**text**`.

Expected Behavior:
When a user formats text as bold within the editor, this formatting should be consistently maintained across all views, including the shared reading page.

Desktop Environment Details:

* OS: macOS 14.2.1
* Browser: Chrome
* Version: 121.0.6167.184 (Official Build) (arm64)

On shared page with view mode

![CleanShot 2024-03-18 at 4  10 38@2x](https://uploads.linear.app/47519575-84a7-4b8b-8a29-c645d1bb39ee/c62228f3-53d1-4902-9001-07ed73ba4b66/b40803cf-16b7-4ae7-bfc3-7d4bbfdf87f6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ3NTE5NTc1LTg0YTctNGI4Yi04YTI5LWM2NDVkMWJiMzllZS9jNjIyMjhmMy01M2QxLTQ5MDItOTAwMS0wN2VkNzNiYTRiNjYvYjQwODAzY2YtMTZiNy00YWU3LWJmYzMtN2Q0YmJmZGY4N2Y2IiwiaWF0IjoxNzExNTAyMTQyLCJleHAiOjMzMjgyMDYyMTQyfQ.I0KeH2k-aSi5OnKUhtIkTZiovTkJSfGCGIinlqGWS0M)

On the page after login or in edit mode

![CleanShot 2024-03-18 at 4  10 58@2x](https://uploads.linear.app/47519575-84a7-4b8b-8a29-c645d1bb39ee/fb261305-8e38-439e-9c56-794988abfd40/bb0627f5-b3ff-4bba-b467-1fb0185f7dd8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ3NTE5NTc1LTg0YTctNGI4Yi04YTI5LWM2NDVkMWJiMzllZS9mYjI2MTMwNS04ZTM4LTQzOWUtOWM1Ni03OTQ5ODhhYmZkNDAvYmIwNjI3ZjUtYjNmZi00YmJhLWI0NjctMWZiMDE4NWY3ZGQ4IiwiaWF0IjoxNzExNTAyMTQyLCJleHAiOjMzMjgyMDYyMTQyfQ.FT3OgQl6EJob0EuOYCraNBdrZ_FKaDr1wIb-UYmt1ak)

**Comment by shepherdwind** [comment] 2024-05-04 06:39
I also encountered this problem. I fixed it in my own fork at https://github.com/shepherdwind/outline/commit/266ff7be334e99598cec0cecb0c27540881c34ae. You can try the image I built at https://hub.docker.com/r/shepherdwind/outline. As for the markdown-it plugin, I will release a separate package.

The root cause of the issue is that markdown-it parses `**==xxx==**xx`-like processes abnormally. When a special character such as `+-=` or a Chinese space here is encountered before the second `**`, it recognizes an unclosable tag, so two open `**` are ultimately output directly. In edit mode, rendering follows a different process, so there are no issues on the editing page.

https://github.com/outline/outline/blob/main/app/scenes/Document/components/Document.tsx#L404-L405

**Comment by tommoor** [comment] 2024-05-27 15:42
fixed by #5553

**Closed by tommoor** 2024-05-27 15:42 UTC
Labels: bug
