### ISSUE TITLE
Request to signup with email with custom domains

### ISSUE THREAD

**Issue by shrsv** [outline/outline#2874] opened 2021-12-21 14:41 UTC
Will it be possible to add support for sign-ups with custom domains? We are a small company with a namecheap email setup, and we could not sign up since personal gmail too was blocked.

**Comment by tommoor** [comment] 2021-12-22 23:06
Duplicate of https://github.com/outline/outline/issues/1881

**Closed by tommoor** 2021-12-22 23:06 UTC
