### ISSUE TITLE
ValidationError: null is not a valid date

### ISSUE THREAD

**Issue by marcelmuehmel** [outline/outline#4027] opened 2022-08-29 07:27 UTC
Outline simply crashes after a while without anyone being on the page with the following error:

**To Reproduce**

**Expected behavior**

```
/opt/outline/node_modules/sequelize/lib/data-types.js:312
      throw new sequelizeErrors.ValidationError(util.format("%j is not a valid date", value));
            ^

ValidationError [SequelizeValidationError]: null is not a valid date
    at DATE.validate (/opt/outline/node_modules/sequelize/lib/data-types.js:312:13)
    at DATE.validate (/opt/outline/node_modules/sequelize/lib/dialects/postgres/data-types.js:126:22)
    at PostgresQueryGenerator.validate (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-generator.js:740:22)
    at PostgresQueryGenerator.format (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-generator.js:724:14)
    at PostgresQueryGenerator.updateQuery (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-generator.js:313:58)
    at PostgresQueryInterface.update (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:352:37)
    at Object.save (/opt/outline/node_modules/sequelize/lib/model.js:2432:79)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    ValidationErrorItem {
      message: 'null is not a valid date',
      type: 'Validation error',
      path: 'expiresAt',
      value: Invalid Date,
      origin: 'FUNCTION',
      instance: null,
      validatorKey: 'DATE validator',
      validatorName: null,
      validatorArgs: []
    }
  ]
}
```

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.65.2

**Comment by tommoor** [comment] 2022-08-30 21:21
> Outline simply crashes after a while without anyone being on the page

This is highly unlikely, can you provide logs surrounding the error

**Comment by tommoor** [comment] 2022-08-31 07:54
Closing as a duplicate of #4040 as that report has more information

**Closed by tommoor** 2022-08-31 07:54 UTC
Labels: bug, more information needed, self-hosted
