### ISSUE TITLE
Pasting in code-block erases text in IceCat & IceWeasel (Firefox)

### ISSUE THREAD

**Issue by mind-overflow** [outline/outline#3065] opened 2022-02-06 13:18 UTC
Pasting in code-blocks erases text preceding what is pasted.

**To Reproduce**
1. Open Outline and log-in
2. Open any document
3. Create a code block
4. Try to paste text in the code block
5. You will notice that by pasting the text, it also erases what was preceding it, only leaving the next part.

**Expected behavior**
It should just paste the text where the cursor is, like it does in other browsers or versions.

**Screenshots**
Not a screenshot, but I uploaded a short [video](https://youtu.be/SQO0Clcf4ko).
*Note: I had a few extensions installed at time of recording, but even after disabling all of them, the issue persists.*
*I also tried changing security settings (third-party cookies, HTTPS everywhere, DoNotTrack, ...) to no avail.*

**Outline:**
- Install: self-hosted
- Version: latest docker available image | 0.61.1, digest e1746492002f

**Desktop:**
 - OS: Windows 11 on Surface Pro 8
 - Browser: IceCat (Firefox) 91.5.0 ESR *and* IceWeasel 98.0
  
**UPDATE**: This also happens on a fresh install of IceWeasel 98.0.
**UPDATE 2**: apparently, this only happens if I try to paste text that I have copied from Outline itself. If I copy-paste something from Windows Notepad, it works fine. My guess is that the browser is also copying some html that Outline doesn't handle perfectly?

**Comment by mind-overflow** [comment] 2022-02-06 14:02
Separate reply because this update is more in-depth.
I have looked at the clipboard's raw data when copying from Chromium, Firefox, IceCat and IceWeasel. And indeed, there is a difference!  
  
This is the Chromium-generated clipboard:
<details>
  <summary>click</summary>
  
![image](https://i.ibb.co/PrZ34jY/chrome.png)
  
  
</details>


This is the Firefox-generated clipboard:
<details>
  <summary>click</summary>
  
![image](https://i.ibb.co/cwQCSCS/firefox-esr.png)
  
  
</details>
It adds a `DataObject` and a `text/html` component. However, standard Firefox is still handled correctly by Outline.


This is the IceCat & IceWeasel generated clipboard:
<details>
  <summary>click</summary>
  
![image](https://i.ibb.co/3v9TC01/icecat.png)
  
  
</details>
In addition to Firefox's stuff, this also adds `text/_moz_htmlcontext` and `text/_moz_htmlinfo` objects.  
  
I think this is why Outline has this issue when content is pasted. Unfortunately, I can't reliably show you the clipboard content because it's binary data, but at least I found a way to replicate it and investigate the issue...

**Comment by tommoor** [comment] 2022-02-06 22:11
It seems unlikely that it's due to the contents of the clipboard because the contents isn't evaluated to replace existing content if that makes sense. Unfortunately I can't reproduce this behavior on macOS, perhaps you could try the [Prosemirror Demo](https://prosemirror.net/examples/basic/) which is the editor framework we use to see if the issue is also present there.

**Comment by tommoor** [comment] 2022-04-30 22:42
Given the small userbase of these browsers and the fact there is nothing we can do here in this repo I'm closing this out for now. If the fix gets made in prosemirror then we'll merge it in.

**Closed by tommoor** 2022-04-30 22:42 UTC
Labels: bug
