### ISSUE TITLE
Outline Support the custom Email & Password Login/Singup Feature?

### ISSUE THREAD

**Issue by hupptechnologies** [outline/outline#6617] opened 2024-03-01 08:40 UTC
I want to use the self hosted the outline with the custom email & password login/singup feature, i don't want to use my members to use the google or social signin option.

**Expected behavior**
custom email & password login/singup feature

**Comment by tommoor** [comment] 2024-03-01 12:28
Duplicate of #1881

**Closed by tommoor** 2024-03-01 12:28 UTC
Labels: bug
