### ISSUE TITLE
Within a table cell, a word might span multiple lines and trigger spellcheck

### ISSUE THREAD

**Issue by feingold-ant** [outline/outline#7298] opened 2024-07-23 20:00 UTC
**To Reproduce**
1. Go to a table
2. Place your cursor within a word and resize the cell / add words until the word spans multiple lines.

Note: I was not personally able to reproduce this behavior, but got the screenshot and description from a customer.

**Expected behavior**
Spellcheck should not activate; the word should not span multiple lines.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

![Screenshot 2024-07-23 at 16 57 44](https://github.com/user-attachments/assets/4c11043a-96aa-4927-a099-9fdfeb13f1e1)

**Outline (please complete the following information):**
- Install: self hosted
- Version: d1445993300c9a46306fe549a44cf59fd4be4ae7

**Comment by tommoor** [comment] 2024-07-24 01:47
I'm also not able to reproduce, this feels like a browser issue – text shouldn't even split in the middle of a word like that. Can you find out which browser was in use?

**Comment by feingold-ant** [comment] 2024-07-24 14:37
Chrome

**Comment by tommoor** [comment] 2024-07-25 00:15
Although I can't reproduce it yet this appears to be caused by the multiplayer cursor in the middle of the word causing it to split into two. You can see the orange vertical bar on the right side, which is someone else in the doc.

**Comment by tommoor** [comment] 2024-08-29 16:53
Closing as unreproducible for now, if you find the combination that triggers this please reopen

**Closed by tommoor** 2024-08-29 16:53 UTC
Labels: bug, editor
