### ISSUE TITLE
SideBar will autohide when it's not chosen

### ISSUE THREAD

**Issue by zwwhdls** [outline/outline#1044] opened 2019-09-19 08:03 UTC
Hi,

When I chosed one sidecar and click another, the clicked one will autohide.
like this:

![CleanShot 2019-09-19 at 15 49 54](https://user-images.githubusercontent.com/33822635/65224491-dbbdc300-daf5-11e9-8597-b0a4f70e1c50.gif)

**Comment by tommoor** [comment] 2019-09-19 15:50
Hey, it's quite hard to tell what's happening here – could you upload a video somewhere perhaps? It looks frustrating though, we'd love to figure out what's happening.

**Comment by zwwhdls** [comment] 2019-09-20 05:49
Hi @tommoor ,

Let me tell a story for you to figure out what's happening...

Seeing in the gif which is in my first comment, I have a collection called "302-Kubernetes". The collection has many documents(from 000 to 013).

Now, I clicked on document 012 and the sidebar became gay which is the chosen status.

Then, I want to see what child documents are in document 000. So I expand the drop dox in document 000 to see its child documents. But, the drop-down box is automatically closed immediately, and I have no time to see what child documents in it. 

What I hope is that when I clicked the doc 012, I can expand the drop box in doc 000 (not click) to see its child docs.

Did I describe the problem clearly this time? Tell me if you can't see the gif and I will upload a video somewhere.

Thankyou!

**Comment by tommoor** [comment] 2019-09-21 19:58
Thanks for the description, unfortunately I've been unable to reproduce. Could you clarify a couple of things:

- Is this on the hosted version of `getoutline.com` or is it self hosted? If self hosted – which version?
- Are there any visible errors in the developer console?

**Comment by zwwhdls** [comment] 2019-09-23 02:21
Hi @tommoor ,

- It's self host, and the version is 0.36.1
- I reproduced the issue and some errors in console:

![image](https://user-images.githubusercontent.com/33822635/65398794-ddd09c00-ddeb-11e9-9976-e2a2460b0147.png)

**Comment by dgadelha** [comment] 2019-09-24 13:17
I'm experiencing the same issue, it happens when you have a collection with a large number of documents and sub-documents, to make it stop auto-closing, you need to open the document. It usually closes itself automatically when scrolling if not selected.

**Comment by tommoor** [comment] 2019-09-24 17:05
I think we're zeroing in…

**Closed** 2019-10-13 23:15 UTC
Labels: bug
