### ISSUE TITLE
Maximum number of connections reached

### ISSUE THREAD

**Issue by 42Fourward** [outline/outline#5446] opened 2023-06-16 13:42 UTC
Hello everyone,
I am having a random problem. On some documents, no one can edit it anymore and access to the server appears as being offline
:
![image](https://github.com/outline/outline/assets/104255647/9769b93b-1691-48d7-a1d6-13bfdd76806f)

What is strange is that you can edit other documents.
In the logs I have this error :
`outline_app  | {"label":"multiplayer","level":"info","message":"Rejected connection to \"document.28131f4e-dd36-489b-8dd5-2af3a3c25c16\" because it has reached the maximum number of connections"}`
To be able to edit the problem document again, I have to restart the container. I disabled the `RATE_LIMITER` thinking that was the cause but it is not.

- Outline version : `0.69.2`
- Access to the server via reverse-proxy (traefik, version `2.10.1`) with let's encrypt certificate
- Authentication is done in OpenIDConnect (via Authelia, version `4.37.5`)
- Postgres version : `15.3`
- Redis version : `7.0.8`
- Stream protected by a WAF container (owasp/modsecurity-crs) via middleware on traefik

An idea ?

**Comment by tommoor** [comment] 2023-06-16 14:42
There is a default maximum of 100 socket connections per document – this means that you've hit that. The connection max can be increased with `COLLABORATION_MAX_CLIENTS_PER_DOCUMENT` environment variable

**Comment by zlyoha** [comment] 2023-09-21 08:06
@tommoor I've encountered the same problem and it happened once. What additional information would be helpful if problem becomes regular?

**Comment by tommoor** [comment] 2023-09-21 11:29
Server logs as far back as you can go

**Comment by S4kur4** [comment] 2023-10-09 09:59
I have encountered this problem twice. When I checked the logs, I found hundreds of the following clips before the connections was rejected:
![image](https://github.com/outline/outline/assets/17521941/55ee844a-bbac-4b41-8c5b-1d182666b442)
New connections were created but closed right away, but I don't have idea why this happen. What I can determine is that the document that rejected connections was not viewed and used by multiple people at the same time. Also users were not refreshing the page frequently. But after tracking the specific user, there is a funny situation may related to this problem is a user kept a specific document page open in his browser but doesn't view it or edit it for a long time. I don't have a final conclusion for this problem, just share the information here to discuss.

**Comment by tommoor** [comment] 2023-10-09 18:54
@S4kur4 what is the timing on these logs? Are they spread over hours or minutes? If hours this could be perfectly normal behavior for a tab that is left open on a laptop for example.

**Comment by S4kur4** [comment] 2023-10-10 02:55
@tommoor Yes, they are generated within a few hours. I noticed that before the occurrence of "Rejected connection", there is a batch of "New connection" events that are not followed by "Closed connection." Interestingly, the number of them is exactly 100, as shown in the figure below:
![20231010103514](https://github.com/outline/outline/assets/17521941/13b84d00-98a3-4aa2-bf4d-9af82a47452d)
Looks like this is where the maximum of socket connections triggered. After this, all connections were rejected and continued for a long time.

**Comment by tommoor** [comment] 2023-10-10 12:50
It seems like the backend is doing the correct thing then, protecting against too many connections being created. The question is where are these coming from and why… are you running a reverse proxy or anything that can better track where the connections originate?

**Comment by S4kur4** [comment] 2023-10-11 03:45
@tommoor Yes I use Nginx as a reverse proxy but the `access.log` for that time are no longer available because this issue is occurred more than a month ago. The document with the problem in an uneditable state from that time, and I solved the problem by restarting docker. I asked every user who viewed that document and only one user hanging it in his browser tab at that time.
If I encounter this issue next time, more detailed information will be provided here.

**Comment by wasdennnoch** [comment] 2023-10-27 19:37
We're also experiencing "connection limit" issues with some of our documents, and I managed to find two scenarios in which Outline doesn't detect when Websockets disconnect, causing the issue in question:

1) Literally just open a websocket to a valid document and then don't send anything over it. After 30 seconds the socket will automatically be closed (or you can close it manually), but Outline will not log that the connection was closed.  
I would say it's not too unreasonable to assume that having random unauthorized websockets could also happen in the wild, such as with bad network connectivity, or perhaps with quickly clicking through different documents so that you click out of a document before the socket had a chance to authenticate.

2) Sending invalid authorization through the socket, causing `onAuthenticate` (in the `AuthenticationExtension`) to throw and close the connection. I imagine this could happen if your jwt has expired?

Doing those things will cause stray connections to be stored in the `ConnectionLimitExtension`, and doing it 100 times will cause the document to forever be stuck at the connection limit until you restart Outline.

Looking at Outline's code, I guess Hocuspocus doesn't call the `onDisconnect` hook in both of these cases. Not sure if that is intended behavior or a bug. For the authorization point, the documentation of the [hook chain](https://tiptap.dev/hocuspocus/server/hooks#the-hook-chain) mentions that throwing in a hook will cause further extensions to not be called, but it's unclear to me if this also applies to socket lifecycle events.

**Closed** 2023-10-28 14:33 UTC
Labels: bug, collaborative editing
