### ISSUE TITLE
Google form embed option

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3129] opened 2022-02-16 16:23 UTC
### Discussed in https://github.com/outline/outline/discussions/3128

<div type='discussions-op-text'>

<sup>Originally posted by **jenningsb2** February 16, 2022</sup>
Hey team! 

I have a google form that I would love to use to capture feedback and interest on my documentation. I see that Google Docs/Sheets/Slides have an embedded option. 

**Would an embedded Google Form be an option?**

Since my company uses Google Workspace, it would be great to be able to stay in their ecosystem.</div>

**Comment by matbrgz** [comment] 2022-02-16 20:35
My first try to do that https://github.com/outline/outline/pull/2291

**Comment by jordanaxani** [comment] 2022-02-27 12:35
Would love this. We use Jotform so would love that too, one day, or alternatively an iframe embed option.

**Comment by matbrgz** [comment] 2022-06-29 21:00
@jordanaxani could you please help me here?

**Comment by apoorv-mishra** [comment] 2022-08-04 11:41
Duplicate of #3923

**Closed by apoorv-mishra** 2022-08-04 11:41 UTC
Labels: enhancement, good first issue
