### ISSUE TITLE
Internal doc link breaks navigation

### ISSUE THREAD

**Issue by mylogon341** [outline/outline#1175] opened 2020-02-12 13:52 UTC
Inserting a link to a neighbouring document causes the navigation to stop working properly.

**Environment:**
Chrome browser. macOS
Self-hosted solution on aws

**Reproduction steps:**
1. Create several nested documents.
2. Create a link to a neighbouring nested document
3. Click the link.

**What should happen:**
You should be able to see the content of the article and should be able to navigate correctly afterwards.

**What does happen:**
The article is blank. Navigation stops working correctly.

**Work around:**
Refresh browser to restore functionality.

**Comment by mylogon341** [comment] 2020-02-12 13:58
Video showing this in action  
https://drive.google.com/file/d/1oLCXYNE5odrvu2ygCdOArluCVQqq4FIJ/view?usp=sharing
Thanks

**Comment by tommoor** [comment] 2020-02-13 03:52
Is the link a relative link created by searching in the link editor or is it an absolute link with http etc?

**Comment by mylogon341** [comment] 2020-02-13 08:58
Ah, it was absolute. I wasn't aware of a relative link feature.
I just tried editing the link to a reference link and it's gone haywire too, unfortunately.
New vid 
https://drive.google.com/file/d/1gGVKVgK9T5chhgWaFRcDerNvWe3Qz2E7/view?usp=sharing

**Comment by tommoor** [comment] 2020-02-13 14:47
It's frustrating that I'm unable to create the same situation as this is clearly a bug that needs fixing immediately. Are there any errors in the console?

**Comment by mylogon341** [comment] 2020-02-13 15:14
sorry nope. nothing related anyway. there is one 
> Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.
But I don't think that's related.
Happy to do a screen share if you want to debug remotely to see if anything stands out to you.

**Comment by tommoor** [comment] 2020-02-13 17:06
If you're in a position to try running code from a branch I believe this will resolve the issue:
https://github.com/outline/outline/pull/1176

**Comment by mylogon341** [comment] 2020-02-13 17:11
Excellent - I'll share it with our sys ops guys and see if they can do some git magic to try it out. It will probably mid next week before I get back to you though, unfortunately.
I'll keep you updated 👍

**Comment by mylogon341** [comment] 2020-02-18 16:58
A hah. So, that fix didnt actually fix the issue. However, i was able to kind of narrow down how to recreate it for you. Basically, if i rename the documents, the linking starts working and i am able to navigate between them freely, but as soon as I put their names back, it breaks again!

So, hopefully this will help you to recreate

Engineering is a collection btw
`Engineering > Mobile > iOS > Guides > Integrating fastlane screenshots` 
and
`Engineering > Mobile > iOS > Guides > Integrating fastlane frameit`
however, if i name the documents "meh" and "blah" they and navigate totally fine. 
I dont know if its a path length issue or... what ... but its definitely a bit of a strange one .  
Hopefully this helps.

**Comment by tommoor** [comment] 2020-02-19 04:05
Thanks for that, I've discovered the error with these reproduction steps 👍

**Comment by mylogon341** [comment] 2020-02-19 12:13
Hi tom. Sorry to be a pain, but we've pulled these changes in and it's still an issue 😢 Do you think there is some sort of 'lingering' but that means we just need to recreate the documents etc to pick up the new changes?
thanks

**Comment by JoeAlamo** [comment] 2020-02-20 16:56
I can confirm this fixed the issue - the changes weren't getting picked up because our docker-compose file was using a pinned outlinewiki/outline image version 😅. Changed it so it builds it based off the Dockerfile and it is working now after a fresh deploy

**Comment by tommoor** [comment] 2020-02-23 01:20
Great, closing as resolved.

**Closed by tommoor** 2020-02-23 01:20 UTC
Labels: bug
