### ISSUE TITLE
MAXIMUM_IMPORT_SIZE fails with 0.75.1

### ISSUE THREAD

**Issue by chris-sanders** [outline/outline#6572] opened 2024-02-21 14:50 UTC
**To Reproduce**
1. Running 0.75.0 with no MAXIMUM_IMPORT_SIZE
2. Switch image to 0.75.1 with no config chages
3. Pod crashes with below message about invalid config

```
yarn run v1.22.19
$ node ./build/server/index.js
The environment variable AWS_S3_UPLOAD_MAX_SIZE is deprecated and will be removed in a future release. Use FILE_STORAGE_UPLOAD_MAX_SIZE instead
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
(node:28) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":"warn","message":"Environment configuration is invalid, please check the following:\n\n"}
{"level":"warn","message":"- MAXIMUM_IMPORT_SIZE must be a number conforming to the specified constraints"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have not been setting this value, and it looks like 0.75.1 actually removed the setting (https://github.com/outline/outline/commit/7c03963be184ceb58687675c2dd6168659d57b39) so I'm not clear why it's failing validation. I'm not sure if this was meant to be taken out of validation or maybe there's a new way to configure this with no defaults now that the user needs to set?

Given it's just a patch update I didn't expect a user configuration change requirement, but if that's what it is any information about what I should be changing would be helpful.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.75.0 -> -.75.1

**Comment by tommoor** [comment] 2024-02-21 14:51
Duplicate of #6571

**Closed by tommoor** 2024-02-21 14:51 UTC
Labels: bug
