### ISSUE TITLE
Authentication emails don't use `SMTP_FROM_EMAIL` as sender

### ISSUE THREAD

**Issue by astappiev** [outline/outline#7980] opened 2024-11-19 10:06 UTC
Sending authentication emails is broken as soon as the SMTP server doesn't allow to send emails from any alias.

https://github.com/outline/outline/blob/326f733d4c06da4e0bcbf5182a8761c6ea745adb/server/emails/templates/BaseEmail.tsx#L178-L199

**To Reproduce**
1. Set an SMTP server which authorizes only FROM email as sender.
2. Try to login using email link.

**Expected behavior**
Emails are sent from `SMTP_FROM_EMAIL` address

**Outline:**
- Install: self-hosted
- Version: v0.81.0

**The error I had because of this (for the purpose of easier finding the issue from search)**
```js
{"error":"Can't send mail - all recipients were rejected: 553 5.7.0 Unauthorized use of sender address (msg ID = ef646daf)","level":"error","message":"Error processing task in EmailTask","stack":"Error: Can't send mail - all recipients were rejected: 553 5.7.0 Unauthorized use of sender address (msg ID = ef646daf)\n    at SMTPConnection._formatError (/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:798:19)\n    at SMTPConnection._actionRCPT (/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:1667:28)\n    at SMTPConnection.<anonymous> (/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:1620:30)\n    at SMTPConnection._processResponse (/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:982:20)\n    at SMTPConnection._onData (/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:763:14)\n    at SMTPConnection._onSocketData (/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:519:28)\n    at TLSSocket.emit (node:domain:488:12)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)"}
```

**Comment by tommoor** [comment] 2024-11-19 12:38
Duplicate of https://github.com/outline/outline/issues/7929

**Closed by tommoor** 2024-11-19 12:38 UTC
Labels: bug
