### ISSUE TITLE
Login issue with /done=<counter> changing counter code

### ISSUE THREAD

**Issue by harinij** [outline/outline#1290] opened 2020-05-27 11:28 UTC
Created a new account and when I login using google account and enter the team setting, seeing the URL with /done=<counter> with random counter continuously changing and the screen goes blank. Has anyone else seen this issue and if so is there any fix for it?

**Comment by ishi-geru** [comment] 2020-05-27 14:53
I'm seeing the same problem.

**Comment by tommoor** [comment] 2020-05-27 15:02
Currently unable to reproduce, could you fill in the bug template – there are a lot of details there that are required to debug this properly.

**Comment by willwade** [comment] 2020-05-28 04:21
I’m getting this on slack login. Eg https://www.getoutline.com/?done=1590639531869 https://share.icloud.com/photos/0GBlhG1Hp4RpRVj_9e4drmMZA

At least I think that’s the same bug. Nb. I already have an account. Just haven’t logged in for ages.

**Comment by tommoor** [comment] 2020-05-28 05:17
Hey folks, thanks for taking the time to file. I can confirm that this issue is resolved in production 🙏

**Closed by tommoor** 2020-05-28 05:17 UTC
Labels: bug, more information needed
