### ISSUE TITLE
Official Heroku Images aren't functional

### ISSUE THREAD

**Issue by DeeGeeTill** [outline/outline#1089] opened 2019-11-28 07:40 UTC
Mirroring this issue from the Spectrum community: https://spectrum.chat/outline/self-hosted/heroku-images-for-outline~b9a15114-6076-4314-aced-95097ff2436a

**Comment by tommoor** [comment] 2019-12-01 02:41
It seems like the error you're running into is related to the postgres setup somehow, this is not an error that's coming from the core Outline code itself.

**Comment by tommoor** [comment] 2019-12-06 00:27
I was able to easily deploy a fresh installation of Outline to heroku with the method, can't reproduce at this time 😞 

https://dashboard.heroku.com/new?template=https://github.com/outline/outline

**Comment by DeeGeeTill** [comment] 2019-12-06 19:43
This image shows my custom configuration (with censored tokens for obvious reasons).
![image](https://user-images.githubusercontent.com/34075000/70351188-50381080-1860-11ea-995f-dfca571a3a9e.png)
(Error is exactly the same, more or less. Log has been posted to spectrum community as well.)

This is all the information I can divulge, unfortunately, as heroku is limited when it comes to manipulating images. I've since also tried to run this on other computers, browsers, phones etc. All have the exact same error.

**Comment by tommoor** [comment] 2019-12-06 20:10
Thanks for the reply, the only think I can see different is that you're deploying in the Europe region – I wonder if postgres is subtly different there? 😬 

I can try later to reproduce.

**Comment by DeeGeeTill** [comment] 2019-12-06 21:25
You were right, it did have something to do with the European version of Postgres on Heroku.
![image](https://user-images.githubusercontent.com/34075000/70357416-c04d9300-186e-11ea-9f9b-158ed52a5346.png)
Unfortunately, however, this resulted in an application error. 
![image](https://user-images.githubusercontent.com/34075000/70357396-b0ce4a00-186e-11ea-96ca-43e36a107d1c.png)
I'll have a look at this again in the morning... 🥱

**Comment by DeeGeeTill** [comment] 2019-12-06 21:27
(Before I go to bed, the actual logs might be helpful, mightn't they? uwu)
``

2019-12-06T21:23:20.272600+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=wikennial-2.herokuapp.com request_id=bf773039-e1dd-4816-b3bb-58e941059f93 fwd="109.180.50.88" dyno= connect= service= status=503 bytes= protocol=https

2019-12-06T21:23:23.163539+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/dashboard" host=wikennial-2.herokuapp.com request_id=18613e8c-5650-4a95-b833-921de73a15e9 fwd="109.180.50.88" dyno= connect= service= status=503 bytes= protocol=https

2019-12-06T21:22:32+00:00 app[heroku-redis]: source=REDIS addon=redis-clean-56571 sample#active-connections=1 sample#load-avg-1m=0.245 sample#load-avg-5m=0.22 sample#load-avg-15m=0.225 sample#read-iops=0 sample#write-iops=0.25833 sample#memory-total=15664264kB sample#memory-free=12849976kB sample#memory-cached=860372kB sample#memory-redis=313912bytes sample#hit-rate=1 sample#evicted-keys=0

2019-12-06T21:26:07.350020+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/dashboard" host=wikennial-2.herokuapp.com request_id=8ba86218-258f-4660-84f0-7f2ed23df57e fwd="109.180.50.88" dyno= connect= service= status=503 bytes= protocol=https

2019-12-06T21:26:18.658828+00:00 app[api]: Starting process with command `heroku logs --tail` by user george@quotennial.tk

2019-12-06T21:25:56+00:00 app[heroku-redis]: source=REDIS addon=redis-clean-56571 sample#active-connections=1 sample#load-avg-1m=0.175 sample#load-avg-5m=0.205 sample#load-avg-15m=0.22 sample#read-iops=0 sample#write-iops=0.033333 sample#memory-total=15664264kB sample#memory-free=12856636kB sample#memory-cached=860224kB sample#memory-redis=313912bytes sample#hit-rate=1 sample#evicted-keys=0

2019-12-06T21:26:29.473376+00:00 heroku[run.2187]: State changed from starting to complete

2019-12-06T21:26:29.414638+00:00 heroku[run.2187]: Awaiting client

2019-12-06T21:26:29.456831+00:00 heroku[run.2187]: Error R13 (Attach error) -> Failed to attach to process

2019-12-06T21:26:29.458020+00:00 heroku[run.2187]: Process exited with status 128```

**Comment by DeeGeeTill** [comment] 2019-12-06 23:05
So, I couldn't get to sleep. Turns out the only issue was that the config variable
`AWS_REGION`
wasn't in the app.json file by default. After setting that, everything went smoothly, up until I tried to sign in, in which the issue #898 triggered. Now I've just got to find a way of modifying the nginx configuration of a heroku app.

**Comment by tommoor** [comment] 2019-12-06 23:06
That's great, we'll get it added – in terms of nginx, you shouldn't need to change anything there – Heroku provides all the tools you need to map to a domain with SSL

**Comment by tommoor** [comment] 2019-12-07 00:48
Heroku `app.json` is updated https://github.com/outline/outline/commit/504aa9f7bb7defe0027e54addb083cb7ba1c6ae5

**Comment by DeeGeeTill** [comment] 2019-12-12 21:10
Thank you for that. (One more thing and then I'll shut up forever I promise)

> in terms of nginx, you shouldn't need to change anything there – Heroku provides all the tools you need to map to a domain with SSL
 
In that case, how do I solve error #898 on a Heroku instance?

**Comment by tommoor** [comment] 2020-01-03 05:23
Sorry for the delay – the issue you referenced has a lot of different folks mentioning different things. If you're still having a specific problem I'd recommend opening a new issue. I'm going to close this one as the Heroku installation has been addressed

**Closed by tommoor** 2020-01-03 05:23 UTC
Labels: question, self-hosted
