### ISSUE TITLE
Cannot import previous export, either from Outline or Notion 

### ISSUE THREAD

**Issue by looeee** [outline/outline#3801] opened 2022-07-18 10:46 UTC
**To Reproduce**
1. Go to either the Outlne or Notion export pages and generate a Zip file (in Notion I'm doing HTML export)
2. Go the the Outline import page and attempt to upload either zip, either by drag and drop or clicking and to open the file dialogue and selecting the zip file.
3. Receive the message

"File not supported – please upload a valid ZIP file "

4. Attempted extracting the files and creating a new zip using 7zip with the same results. It seems no file with a .zip extension is accepted. 

Attached is the outline zip (can't share Notion export as it has private data)

[outline.zip](https://github.com/outline/outline/files/9131220/outline.zip)

**Notes**

1. There are no console errors.
2. There are no relevant logs in the Outline container in Portainer 
3. I attempted editing the input element in various ways such as removing the `accept="application/zip"`, it does not make any difference. 

**Expected behavior**

The zip file should be uploaded to Outline and the previous export should be restored. 

**Screenshots**

![outline zip error](https://user-images.githubusercontent.com/5307958/179494774-c3035748-0f81-4a57-a918-df491dbcb76c.png)

**Outline (please complete the following information):**
- Install: self hosted via docker 
- Version: docker image: `outlinewiki/outline:0.64.4`

**Desktop:**
 - OS: Windows 10
 - Browser: Tested in Chrome 103.0.5060.114 and Firefox 102.0.1 (both with all extensions disabled)

**Mobile:**
NA

**Comment by looeee** [comment] 2022-07-18 11:08
OK I found a workaround. I saved the file to dropbox then opened outline on my phone (in Chrome). The file was accepted there and the Notion import worked. 

Well. I say _worked_ but I don't think the results are useable. There's a lot data missing and a lot of formatting messed up so I think it will be about the same amount of work (probably more) to fix this up compared to manually copying over the data. That's a separate issue though. 

As for this issue, it seems to be a windows issue.

**Comment by tommoor** [comment] 2022-07-18 11:58
Feels like a duplicate of #3632 – as for the import quality, the functionality is new and it's had limited test data so if you can send over anything that didn't import well we can look into it. You have to bear in mind that Outline only supports some of Notion's functionality so it's never 1-1.

**Closed by tommoor** 2022-07-18 11:58 UTC
Labels: bug
