### ISSUE TITLE
Couldn't find a package.json

### ISSUE THREAD

**Issue by hapiben** [outline/outline#789] opened 2018-10-25 09:13 UTC
Hi,

I was trying to follow the Docker development steps. However, I'm getting this error after running the `make up` command.

```
→ make up
docker-compose up -d redis postgres s3
Starting outline_postgres_1 ... done
Starting outline_s3_1       ... done
Starting outline_redis_1    ... done
docker-compose run --rm outline bash -c "yarn && yarn sequelize db:migrate"
Starting outline_postgres_1 ... done
Starting outline_redis_1    ... done
Starting outline_s3_1       ... done
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Lockfile not saved, no dependencies.
Done in 0.76s.
yarn run v1.6.0
error Couldn't find a package.json file in "/opt/outline"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [up] Error 1
```

Any ideas and help is much appreciated.

Cheers!

**Comment by tommoor** [comment] 2018-10-25 09:17
Strange, not seen this before – try running `docker-compose build` and see if that helps

**Comment by hapiben** [comment] 2018-10-25 20:06
Hi @tommoor,

Thanks for your reply. I tried running

```
→ docker system prune
```

to clear everything. Then `docker-compose build && make up` command again. I'm still getting the same issue. I'm using Mojave.

**Comment by tommoor** [comment] 2018-11-15 07:02
closing as unreproducible, sorry. Let me know if you were able to figure it out – I suspect this is some issue with your local docker installation

**Closed by tommoor** 2018-11-15 07:02 UTC
Labels: question, self-hosted

**Comment by simonkuang** [comment] 2019-07-15 04:03
I got the same error while running `docker-compose up -d`.

> [root@master outline] (master) 31h58m # docker logs 8d9a92ec5a67
> yarn run v1.6.0
> error Couldn't find a package.json file in "/opt/outline"
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

It's because SELinux enabled.

execute the command `chcon -Rt svirt_sandbox_file_t .` in the outline directory, and run docker-compose again, it works.

info: https://stackoverflow.com/questions/43586624/kubernetes-hostpath-storage-permissions
