### ISSUE TITLE
New Columns/Lines on Table in a Mac Computer using Safari Freeze the Page

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1647] opened 2020-11-11 14:44 UTC
.
**To Reproduce**
1. Create new Doc
2. Create a Table
3. Try to create many line/columns fastly

**Expected behavior**
Create new line/colum

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.49.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version Latest

**Comment by tommoor** [comment] 2020-11-11 19:28
Seems to be an infinite loop, I'm able to reproduce in the `rich-markdown-editor` repo alone but the document must be completely empty except the table – if there is content above/below the table then it doesn't reproduce.

Perhaps this helps you work around the issue until a fix is in place.

**Comment by tommoor** [comment] 2020-11-11 22:58
Amazingly, this seems to be the same issue as filed on Prosemirror here in 2019:
https://github.com/ProseMirror/prosemirror/issues/947

**Closed** 2020-11-12 05:35 UTC
Labels: bug, editor, performance
